import type { PracticeProblem } from "../types";

export const problems: PracticeProblem[] = [
  {
    id: "circuits_rc_transient_scope",
    slug: "concept-circuits-rc-transient-scope",
    title: "Reading an RC Step Response on the Bench",
    prompt: "A 10k resistor is in series with a 1uF capacitor, fed by a function generator producing a square wave that swings 0V to 5V. You probe the voltage across the capacitor on an oscilloscope.",
    discipline: "ELECTRICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["circuits", "conceptual"],
    skillAreas: ["circuits"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Describe the shape of the capacitor voltage during one half-period when the input jumps from 0V to 5V, and explain physically what sets how fast it rises. Roughly how long does it take to look fully charged?", rubric: "Should identify the exponential charging curve Vc = Vfinal*(1 - e^(-t/tau)) approaching 5V. Should state tau = R*C = 10k * 1uF = 10ms and that the cap is ~99 percent charged after about 5 time constants (about 50ms). Should explain physically: the resistor limits current, current charges the cap, and as Vc rises the voltage across R shrinks so current (dV/dt) tapers off, giving the exponential. Key insight: the time constant tau = RC, not the source voltage, governs the speed of the response; the final value is set by the source.", },
      { prompt: "Now the square wave frequency is increased until the period is much shorter than one time constant. What does the capacitor voltage waveform look like now, and what circuit function does this configuration approximate at this frequency?", rubric: "Should reason that if the period is much less than tau, the cap never gets close to fully charging or discharging, so Vc rides near the average (a small triangular ripple around the DC average, here ~2.5V). Should recognize the RC behaves as a low-pass filter / integrator at high frequency: it attenuates the fast edges and passes/settles to the DC average. May note Vout across the cap approximately integrates the input when the period is short relative to tau. Key insight: the same RC circuit changes character with frequency relative to tau; well above the cutoff it acts as an integrator/low-pass and the fast square wave is smoothed toward its DC average.", },
    ],
  },
  {
    id: "circuits_thevenin_loading",
    slug: "concept-circuits-thevenin-loading",
    title: "Why the Voltage Sags Under Load",
    prompt: "A sensor module outputs what the datasheet calls a 3.3V reference. With nothing connected you measure exactly 3.3V, but when you connect a 1k load the voltage drops to 2.7V.",
    discipline: "ELECTRICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["circuits", "conceptual"],
    skillAreas: ["circuits"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Using a Thevenin model of the source, explain why the output dropped from 3.3V to 2.7V under load, and estimate the source's Thevenin (output) resistance.", rubric: "Should model the source as Vth = 3.3V in series with Rth. With the 1k load, the output is a voltage divider: Vout = Vth * Rload/(Rth + Rload). Plugging in 2.7 = 3.3 * 1000/(Rth + 1000) gives Rth approximately 222 ohms. Should explain loading: drawing current through Rth drops voltage across it, so the terminal voltage falls. Key insight: the open-circuit (no-load) reading equals Vth; the drop under load reveals nonzero Thevenin resistance, and any real source has finite output impedance.", },
      { prompt: "A colleague suggests buffering this reference with a unity-gain op-amp follower before the load. Explain how that fixes the sag, and what new limitation now sets how much current you can draw.", rubric: "Should explain the op-amp follower presents a very high input impedance (negligible loading of the sensor, so its node stays near 3.3V) and has a very low output impedance (so the load no longer forms a significant divider, output stays near 3.3V). Should note the new limit is the op-amp's output current capability (output drive / short-circuit current) and its supply rails / output swing, not the sensor's Rth. Key insight: a buffer decouples source from load by transforming impedance levels (high in, low out); the binding constraint shifts to the op-amp's output drive rather than the source's internal resistance.", },
    ],
  },
  {
    id: "circuits_cap_blocks_dc",
    slug: "concept-circuits-cap-blocks-dc",
    title: "Why a Capacitor Blocks DC but Passes AC",
    prompt: "In an audio amplifier you see a capacitor placed in series between one gain stage and the next, often called a coupling or blocking capacitor.",
    discipline: "ELECTRICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["circuits", "conceptual"],
    skillAreas: ["circuits"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain physically and in terms of impedance why this series capacitor blocks the DC bias of one stage from reaching the next, yet lets the audio signal through.", rubric: "Should explain capacitor impedance Zc = 1/(j*w*C): at DC (w=0) the impedance is infinite (open circuit), so steady DC bias cannot pass; at audio frequencies the impedance is finite and small, so the AC signal passes. Physically, a capacitor only conducts via charge that changes with time (i = C*dV/dt); constant DC means dV/dt = 0 so no steady current flows, while a time-varying signal pushes charge back and forth across the plates. Key insight: a series capacitor is a high-pass element whose impedance falls with frequency, so it strips the DC operating point while coupling the time-varying signal.", },
      { prompt: "The coupling capacitor together with the next stage's input resistance sets a high-pass corner. If you find the bass frequencies are being attenuated, which way should you change the capacitor value and why, and what is the tradeoff?", rubric: "Should identify the high-pass corner fc = 1/(2*pi*R*C) formed by the coupling cap and the following stage's input resistance R. To pass lower (bass) frequencies, lower the corner frequency, which means increase C (or increase R). Tradeoff: a larger capacitor is physically bigger/more expensive, may require an electrolytic with polarity and leakage concerns, and a very low corner lengthens settling/turn-on transients (longer time constant, slower recovery from DC offsets or clicks). Key insight: increasing C lowers the high-pass cutoff to preserve bass, at the cost of size, component type constraints, and slower transient settling.", },
    ],
  },
  {
    id: "circuits_opamp_virtual_short",
    slug: "concept-circuits-opamp-virtual-short",
    title: "The Virtual Short in a Feedback Op-Amp",
    prompt: "An ideal op-amp is wired as an inverting amplifier: the input signal feeds the inverting input through R1, a feedback resistor Rf connects output to the inverting input, and the non-inverting input is tied to ground.",
    discipline: "ELECTRICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["circuits", "conceptual"],
    skillAreas: ["circuits"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain the concept of the virtual short (virtual ground here) and use it, together with KCL at the inverting input, to derive why the gain is -Rf/R1.", rubric: "Should state that with negative feedback and very high open-loop gain, the op-amp drives its output so the two inputs are forced to nearly equal voltage (virtual short); since the non-inverting input is grounded, the inverting input sits at ~0V (virtual ground). Ideal op-amp draws no input current, so KCL at the inverting node: current through R1 (Vin/R1) equals current through Rf (-Vout/Rf), giving Vin/R1 = -Vout/Rf, hence Vout/Vin = -Rf/R1. Key insight: the virtual short is a consequence of negative feedback plus huge open-loop gain, and combined with zero input current it makes the closed-loop gain depend only on the resistor ratio.", },
      { prompt: "Now suppose the op-amp is not ideal: its open-loop gain is large but finite, say 100,000, and it has limited bandwidth. How does the virtual short assumption break down, and what does this imply for the gain at high frequency?", rubric: "Should explain that with finite open-loop gain A, the inputs are not exactly equal: the differential input voltage equals Vout/A (small but nonzero), so the virtual ground has a small error, and closed-loop gain is slightly less than -Rf/R1 with a gain error proportional to 1/(loop gain). With limited bandwidth, open-loop gain rolls off (gain-bandwidth product is roughly constant), so at high frequency A drops, loop gain shrinks, the virtual short degrades, and closed-loop gain falls off and gains phase shift. Eventually closed-loop bandwidth is set by GBW/closed-loop-gain. Key insight: the virtual short holds only while loop gain is large; as finite gain and bandwidth shrink the loop gain, the virtual ground develops error and the closed-loop gain departs from the ideal resistor ratio, especially at high frequency.", },
    ],
  },
  {
    id: "circuits_rlc_resonance",
    slug: "concept-circuits-rlc-resonance",
    title: "Resonance and Q in a Series RLC",
    prompt: "A series RLC circuit (R, L, and C in series) is driven by a sinusoidal source whose frequency you can sweep. You monitor the current amplitude as you vary frequency.",
    discipline: "ELECTRICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["circuits", "conceptual"],
    skillAreas: ["circuits"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain what happens to the current at the resonant frequency and why, in terms of the inductor and capacitor impedances. What sets the resonant frequency?", rubric: "Should state at resonance the inductive reactance and capacitive reactance are equal and opposite (j*w*L cancels 1/(j*w*C)), so they cancel and the net reactance is zero, leaving only R. The total impedance is minimized (= R) so current is maximized at resonance. Resonant frequency w0 = 1/sqrt(L*C), or f0 = 1/(2*pi*sqrt(L*C)). Should note the current and source voltage are in phase at resonance (power factor = 1). Key insight: at series resonance the reactances cancel, impedance collapses to R, and current peaks; the resonant frequency depends only on L and C, not R.", },
      { prompt: "Now you want a sharper, more selective peak (higher Q) without changing the resonant frequency. Which component should you change and in which direction, what is the tradeoff, and how does Q relate to the bandwidth of the peak?", rubric: "Should identify that for a series RLC, Q = (1/R)*sqrt(L/C) = w0*L/R, so to raise Q without moving f0 (keep L*C fixed) you decrease R (lower series resistance/losses), or increase the L/C ratio while holding L*C constant (larger L, smaller C). Should give bandwidth relation: BW = w0/Q (or f0/Q), so higher Q means a narrower, more selective peak. Tradeoff: very high Q means a very narrow band (less tolerance to component drift, ringing/longer transient settling, and larger peak voltages across L and C that can stress components). Key insight: Q sets selectivity via BW = f0/Q; lowering R (or raising L/C at fixed L*C) sharpens the peak, at the cost of narrower bandwidth, more ringing, and high reactive voltages.", },
    ],
  },
  {
    id: "circuits_rl_inductive_kick",
    slug: "concept-circuits-rl-inductive-kick",
    title: "The Inductive Kick When a Relay Turns Off",
    prompt: "A microcontroller drives a relay coil through an NPN transistor. The coil is an inductor. The circuit works, but every time the transistor switches the coil off, the transistor eventually fails or you see large voltage spikes.",
    discipline: "ELECTRICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["circuits", "conceptual"],
    skillAreas: ["circuits"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Using the inductor's voltage-current relationship, explain why a large voltage spike appears across the transistor at the instant it switches the coil off.", rubric: "Should use V = L*di/dt: an inductor resists sudden changes in current because current cannot change instantaneously through it. When the transistor opens quickly, di/dt is very large and negative, so V = L*di/dt produces a very large voltage spike (the inductive kick / flyback) that appears across the now-open transistor, exceeding its breakdown rating. Should note the energy stored in the field (0.5*L*I^2) must go somewhere. Key insight: because an inductor opposes abrupt current change, interrupting its current fast forces a huge V = L*di/dt spike that can destroy the switching device.", },
      { prompt: "The standard fix is a flyback (freewheeling) diode across the coil. Explain how it protects the transistor, and what design tradeoff arises if you add a series resistor with that diode or use a Zener instead.", rubric: "Should explain the flyback diode is placed across the coil reverse-biased during normal operation; when the transistor turns off, the collapsing field forward-biases the diode, giving the coil current a path to freewheel and decay gently, clamping the spike to about one diode drop above the supply and dissipating the stored energy in the loop resistance. Tradeoff: a plain diode makes current decay slowly (long L/R time constant), which slows relay release/dropout. Adding a series resistor or a Zener clamps to a higher (but still safe) voltage, dissipating energy faster so the current decays faster and the relay releases quicker, at the cost of higher (but bounded) voltage stress on the transistor. Key insight: the diode gives the inductor current a safe freewheel path that limits the spike; trading a higher clamp voltage (resistor/Zener) for faster current decay speeds relay turn-off but increases the voltage the transistor must withstand.", },
    ],
  },
];
