import type { PracticeProblem } from "../types";

export const problems: PracticeProblem[] = [
  {
    id: "transport_phenomena_blowing_on_soup",
    slug: "concept-transport-phenomena-blowing-on-soup",
    title: "Why Blowing on Hot Soup Works",
    prompt: "A person blows steadily across the surface of a bowl of hot soup to cool it faster than letting it sit still.",
    discipline: "CHEMICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["transport-phenomena", "conceptual"],
    skillAreas: ["transport-phenomena"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: In terms of heat transfer mechanisms, explain physically why blowing cools the soup faster than still air. What is the dominant resistance and how does the moving air attack it?", rubric: "Excellent answer: heat leaves the surface through a thermal boundary layer (film) of nearly stagnant air; this gas-side film is the controlling resistance because still air has low thermal conductivity and relies on slow natural convection. Blowing forces convection, thinning the boundary layer and raising the heat transfer coefficient h in Q = h*A*dT. Also enhanced evaporative (mass-transfer) cooling: moving air sweeps away the saturated vapor layer, increasing the vapor concentration gradient and latent heat removal. Should distinguish conduction within the liquid from convection at the interface. Key insight: the air-side film is the bottleneck, and forced convection cools by thinning that film (and refreshing the vapor gradient), not by changing the soup's internal conduction.", },
      { prompt: "Part 2: Now the constraints change. Suppose the soup is in a tall, narrow insulated thermos with only a small opening at the top, and the person blows across that small opening. Why is blowing now far less effective, and what now limits the cooling rate?", rubric: "Excellent answer: with a small opening and insulated walls, the surface area A exposed to convection is tiny and side losses are blocked, so even a large h yields little Q because Q = h*A*dT and A is the limiter. The internal liquid is now controlled by slow natural convection / conduction within the deep thermos, so heat from the bulk cannot reach the surface fast; the internal resistance and the small interfacial area dominate, not the air film. Blowing only thins a film over a small patch. Mention stratification: hot liquid may stay near the top, but transport to the small surface is the new bottleneck. Key insight: the controlling resistance has shifted from the gas-side film to the small surface area and internal transport, so improving h barely helps.", },
    ],
  },
  {
    id: "transport_phenomena_chilton_colburn_dryer",
    slug: "concept-transport-phenomena-heat-mass-analogy-dryer",
    title: "Heat-Mass Analogy in a Dryer",
    prompt: "An engineer measured the heat transfer coefficient for hot air flowing over a wet flat sheet in a dryer and now wants to estimate the drying (evaporation) rate without running a separate mass-transfer experiment.",
    discipline: "CHEMICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["transport-phenomena", "conceptual"],
    skillAreas: ["transport-phenomena"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain the physical basis for the momentum-heat-mass transfer analogy that lets you infer a mass transfer coefficient from a measured heat transfer coefficient. Why are Pr and Sc the central dimensionless groups, and what assumption about the boundary layers must hold?", rubric: "Excellent answer: momentum, heat, and species are all transported by the same eddy/molecular mechanisms across the boundary layer, so their transport equations have the same form. The analogy (Reynolds, Chilton-Colburn j-factors) holds because the velocity, thermal, and concentration boundary layers have similar shapes. Pr = momentum diffusivity / thermal diffusivity (nu/alpha) sets thermal vs velocity layer thickness ratio; Sc = nu/D_AB sets concentration vs velocity layer thickness ratio. Chilton-Colburn: j_H = (h/(rho*cp*U))*Pr^(2/3) equals j_M = (k_c/U)*Sc^(2/3); equate to get k_c from h. Requires similar boundary layers, no strong form drag (or same for both), low mass-transfer rates, and analogous boundary conditions. Key insight: because heat and mass are carried by the same flow structure, the ratio of their coefficients is fixed by (Sc/Pr)^(2/3), so one measurement gives the other.", },
      { prompt: "Part 2: Now the constraints change. The drying air becomes humid and the evaporation rate becomes very high, so there is a strong net flux of vapor leaving the surface. Why does the simple analogy break down here, and how should the engineer correct the estimate?", rubric: "Excellent answer: the analogy assumes low mass-transfer rates so the velocity field is undisturbed; a high net molar flux of vapor away from the wall (Stefan flow / blowing) thickens the boundary layer and distorts the analogous profiles, reducing the effective coefficient relative to the low-flux value. Humidity reduces the driving concentration difference (lower gradient, slower drying). Corrections: apply a blowing/Ackermann-type correction factor or log-mean (film) correction to account for the convective bulk flow superimposed on diffusion; recompute the driving force with actual humidity (partial pressure or mole fraction difference). Also high flux couples heat and mass (evaporative cooling lowers surface temperature, changing the vapor pressure). Key insight: at high flux the bulk convective sweep alters the boundary layer so the unmodified j-factor analogy over-predicts; a blowing correction and the correct humidity driving force are needed.", },
    ],
  },
  {
    id: "transport_phenomena_packed_bed_reactor_film",
    slug: "concept-transport-phenomena-external-film-resistance",
    title: "Film Resistance in a Catalytic Reactor",
    prompt: "A gas-phase catalytic reaction runs in a packed bed of solid catalyst pellets. The lab reports that increasing the gas flow rate (at constant temperature and total throughput per pass) increases the observed reaction rate, even though the intrinsic chemistry should not depend on flow.",
    discipline: "CHEMICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["transport-phenomena", "conceptual"],
    skillAreas: ["transport-phenomena"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain why a higher gas velocity raises the observed rate. What transport resistance is being reduced, and what does this tell you about the rate-limiting step?", rubric: "Excellent answer: the reactant must diffuse from the bulk gas through a stagnant external film around each pellet to reach the catalyst surface; this external mass-transfer film is a resistance in series with the reaction. If the observed rate rises with velocity, the process is partly or wholly external mass-transfer limited: higher velocity raises Re, thins the boundary layer, increases k_c (Sherwood number rises), and steepens the concentration gradient so more reactant reaches the surface. Series-resistance picture: 1/rate ~ 1/(k_c*a) + 1/k_rxn. Velocity dependence implicates the film, not the kinetics. Key insight: flow-rate sensitivity is the diagnostic signature of external film mass-transfer control, because only the transport step depends on velocity while the intrinsic kinetics do not.", },
      { prompt: "Part 2: Now the constraints change. The engineer keeps raising the flow rate, and beyond a certain point the observed rate stops increasing and plateaus. What is now limiting the rate, and what experiment would distinguish the new regime?", rubric: "Excellent answer: once the external film resistance is made negligible, the rate becomes controlled by either the intrinsic surface kinetics or internal (pore) diffusion within the pellet, neither of which depends on bulk velocity, so the rate plateaus. To distinguish: vary pellet size (or crush pellets) at high flow; if rate rises as pellet size shrinks, internal pore diffusion (low effectiveness factor, Thiele modulus) was limiting; if rate is independent of pellet size, it is reaction-rate (kinetic) controlled. Also check temperature dependence: kinetic control gives high apparent activation energy, pore diffusion gives roughly half that, film control gives very low. Key insight: removing the external film exposes the next resistance in series; velocity-independence plus pellet-size and activation-energy tests separate pore-diffusion control from true kinetic control.", },
    ],
  },
  {
    id: "transport_phenomena_pr_oil_vs_mercury",
    slug: "concept-transport-phenomena-prandtl-boundary-layers",
    title: "Prandtl Number and Boundary Layers",
    prompt: "The same pipe and the same flow geometry are used to heat two different fluids: a heavy lubricating oil (high Prandtl number) and liquid metal (very low Prandtl number).",
    discipline: "CHEMICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["transport-phenomena", "conceptual"],
    skillAreas: ["transport-phenomena"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain what the Prandtl number physically represents and how it sets the relative thickness of the velocity and thermal boundary layers for these two fluids. What does that imply about where the temperature drop is concentrated?", rubric: "Excellent answer: Pr = nu/alpha = momentum diffusivity / thermal diffusivity, comparing how fast momentum spreads versus how fast heat spreads. For high-Pr oil, momentum diffuses much faster than heat, so the velocity boundary layer is much thicker than the thin thermal boundary layer; the temperature change is concentrated in a thin layer near the wall, giving a steep wall temperature gradient. For low-Pr liquid metal, heat diffuses faster than momentum, so the thermal boundary layer is much thicker than the velocity layer and heat penetrates far into the flow. Ratio delta_thermal/delta_velocity ~ Pr^(-1/3) roughly. Key insight: Pr fixes the ratio of thermal to velocity boundary-layer thickness, so high Pr puts the entire temperature drop in a thin near-wall film while low Pr spreads it across the channel.", },
      { prompt: "Part 2: Now the constraints change. You must select or design a Nusselt-number correlation for each fluid. Why can a correlation that works well for the oil give poor predictions for the liquid metal, and what physical feature must the metal correlation capture?", rubric: "Excellent answer: standard turbulent correlations like Dittus-Boelter (Nu = 0.023*Re^0.8*Pr^0.4) were fit for ordinary fluids (Pr roughly 0.7 to ~100) where heat transport is dominated by turbulent eddies in a thin thermal layer. For liquid metals (Pr << 1), molecular conduction carries significant heat even in the turbulent core because the thermal layer is thick and conduction is fast, so eddy transport is not dominant; the Pr^0.4 scaling fails and Nu does not vanish as turbulence weakens. Metal correlations use the Peclet number (Pe = Re*Pr) and have a nonzero conduction-limited floor, e.g. Nu = a + b*Pe^c (Seban-Shimazaki / Notter-Sleicher forms). Key insight: liquid metals carry heat by molecular conduction even in turbulent flow, so the correlation must be Peclet-based with a conduction floor rather than the eddy-dominated Reynolds/Prandtl form valid for the oil.", },
    ],
  },
  {
    id: "transport_phenomena_stirred_tank_mixing",
    slug: "concept-transport-phenomena-mixing-diffusion-convection",
    title: "Why Stirring Beats Diffusion",
    prompt: "Two beakers each receive a drop of dye. One is left perfectly still; the other is gently stirred. The stirred beaker becomes uniform in seconds while the still one takes hours.",
    discipline: "CHEMICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["transport-phenomena", "conceptual"],
    skillAreas: ["transport-phenomena"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain why stirring dramatically accelerates mixing, in terms of convection versus diffusion and the length scales involved. Why is molecular diffusion alone so slow over centimeter distances?", rubric: "Excellent answer: in the still beaker, transport is by molecular diffusion only; the time to diffuse a distance L scales as t ~ L^2 / D, and because D for liquids is tiny (~1e-9 m^2/s) and L is centimeters, this is enormous (hours). Stirring adds convection (bulk advection), which physically carries packets of fluid across the beaker quickly and, more importantly, stretches and folds the fluid to reduce the striation/diffusion length scale to very small values. Diffusion then only has to act over those tiny scales, and since t ~ L^2/D, shrinking L drastically cuts the time. Peclet number Pe = U*L/D >> 1 means convection dominates. Final homogenization at the molecular level still requires diffusion, but over micro-scales. Key insight: diffusion time grows as L^2, so stirring wins by convecting fluid around and slashing the diffusion length, not by speeding up diffusion itself.", },
      { prompt: "Part 2: Now the constraints change. The beaker contents are extremely viscous (think honey or polymer melt) and the same gentle stirring is applied. Why does mixing become much harder, and what changes about the transport picture?", rubric: "Excellent answer: high viscosity means low Reynolds number, so the flow is laminar and turbulence cannot develop; there are no chaotic eddies to stretch and fold the fluid efficiently. Mixing relies on laminar stretching/folding (chaotic advection) which is slow and depends strongly on stirrer geometry; without it you get smooth shearing that may leave unmixed regions and islands. Diffusion is also slower (D often lower in viscous media), so the back-up mechanism is weak. The Peclet number is very high (poor diffusive smoothing) while Reynolds is low (poor convective chaos), the worst combination. Need special tools: high shear, time-periodic or asymmetric protocols to induce chaotic advection, static mixers. Key insight: at high viscosity laminar flow removes the turbulent eddies that normally cut the diffusion length, so mixing must rely on deliberate stretching and folding rather than turbulence.", },
    ],
  },
  {
    id: "transport_phenomena_wetted_wall_two_film",
    slug: "concept-transport-phenomena-two-film-gas-absorption",
    title: "Controlling Film in Gas Absorption",
    prompt: "A gas absorber removes a contaminant from air by contacting it with a flowing liquid solvent. The design team must decide whether to spend money improving gas-side turbulence or liquid-side turbulence to boost absorption.",
    discipline: "CHEMICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["transport-phenomena", "conceptual"],
    skillAreas: ["transport-phenomena"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Using the two-film theory, explain how the solute's solubility (Henry's law constant) determines whether the gas film or the liquid film controls the overall mass transfer resistance. Give the resistances-in-series relationship.", rubric: "Excellent answer: two-film theory puts a gas film and a liquid film in series at the interface, with equilibrium (Henry's law, p = H*x or via m = dy/dx) at the interface. Overall resistance: 1/K_y = 1/k_y + m/k_x (gas-phase overall) where m is the slope of the equilibrium line (proportional to H). For a highly soluble gas (small H, small m), the m/k_x term is negligible so the gas film controls. For a sparingly soluble gas (large H, large m), the m/k_x term dominates so the liquid film controls. The individual coefficients k_y and k_x are comparable, so solubility decides via m. Key insight: solubility, through the equilibrium slope m, weights the two series resistances, so highly soluble gases are gas-film controlled and poorly soluble gases are liquid-film controlled.", },
      { prompt: "Part 2: Now the constraints change. The contaminant is highly soluble in the solvent and reacts rapidly once dissolved. Where should the design effort go, and how does a fast liquid-phase reaction shift the controlling resistance and the strategy?", rubric: "Excellent answer: a highly soluble gas is already gas-film controlled, so the money should go to improving gas-side turbulence (raise k_y) to increase Q since the liquid resistance is already small. A fast liquid-phase reaction consumes the solute right at the interface, steepening the liquid-side gradient and effectively boosting the liquid coefficient by an enhancement factor (Hatta number / E), shrinking the liquid resistance even further. This reinforces gas-film control, so liquid-side mixing investment gives little return. Strategy: maximize gas-film transfer and interfacial area; the reaction also lets the driving force stay near the full partial pressure since interface liquid concentration stays low. Key insight: high solubility plus a fast reaction collapse the liquid-side resistance, locking the system in gas-film control, so design effort belongs on gas-side turbulence and interfacial area, not liquid mixing.", },
    ],
  },
];
