import type { PracticeProblem } from "../types";

export const problems: PracticeProblem[] = [
  {
    id: "electromagnetics_pcb_clock_loop_emi",
    slug: "concept-electromagnetics-clock-loop-emi",
    title: "Radiated EMI from a Clock Trace",
    prompt: "A digital board fails radiated emissions testing with a strong peak at the clock frequency. The clock trace runs across a split in the ground plane to reach a connector.",
    discipline: "ELECTRICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["electromagnetics", "conceptual"],
    skillAreas: ["electromagnetics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain physically why routing the clock across a ground-plane split causes excess radiated emission. Use the idea of current return paths and loop area.", rubric: "Should explain that high-frequency return current wants to flow directly beneath its signal trace (lowest inductance path), not back through the DC-shortest path. A split in the plane forces the return current to detour around the gap, creating a large signal-plus-return current loop. Radiated emission scales with loop area and with the time-varying current (a loop antenna; far-field roughly proportional to f^2 * area * current). Larger loop = larger magnetic dipole moment = more radiation, concentrated at the clock harmonics. Key insight: high-frequency return current follows the path of least inductance directly under the trace, so any break in that path enlarges the radiating loop.", },
      { prompt: "Now suppose you cannot move the trace or remove the split. What design changes would reduce the emission, and why does each one work?", rubric: "Should propose: add a stitching capacitor (or stitch the planes) bridging the split near the crossing to give return current a short high-frequency path, shrinking the loop; slow the edge rate / reduce slew (lower dV/dt and dI/dt cuts high harmonics since spectral content rolls off above 1/(pi*tr)); use a series source-termination resistor to damp ringing; add a guard or return trace alongside the clock to provide a local return; shield or filter at the connector. Each works by either reducing the radiating loop area or reducing the high-frequency current content. Key insight: you fix radiated EMI by attacking the two factors that set it, namely loop area and the spectral amplitude of dI/dt.", },
    ],
  },
  {
    id: "electromagnetics_transformer_inrush_lenz",
    slug: "concept-electromagnetics-faraday-lenz-coil",
    title: "Faraday, Lenz, and a Dropped Magnet",
    prompt: "A strong magnet is dropped down a vertical copper tube and is observed to fall noticeably slower than it would in free fall, even though copper is non-magnetic.",
    discipline: "ELECTRICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["electromagnetics", "conceptual"],
    skillAreas: ["electromagnetics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain using Faraday induction and Lenz's law why the magnet falls slowly, and identify what determines the terminal-like velocity it reaches.", rubric: "Should explain that the moving magnet creates a changing magnetic flux through loops of the conductive tube wall, inducing eddy currents (Faraday: EMF proportional to -dPhi/dt). By Lenz's law these currents oppose the change, so their magnetic field repels the approaching pole and attracts the receding pole, producing a retarding (drag) force. The drag force grows with velocity; the magnet approaches a steady speed where magnetic drag balances gravity (mg). Higher conductivity and thicker walls give more eddy current and more drag, hence slower fall. Key insight: induced eddy currents always oppose the motion that creates them, so the conductor acts like a velocity-dependent magnetic brake.", },
      { prompt: "Now you cut a single vertical slit down the full length of the tube. Predict what happens to the falling speed and explain why.", rubric: "Should predict the magnet falls much faster (closer to free fall). The slit breaks the circumferential (azimuthal) current loops that the eddy currents need to flow in; with the loop interrupted, large eddy currents cannot circulate, so the induced opposing field and the braking force collapse. Some smaller currents may still flow in residual paths, giving slight damping, but far less. Reinforces that braking requires a closed conductive loop for current. Key insight: eddy-current braking depends on a continuous closed path for the induced current, so interrupting that path removes the drag.", },
    ],
  },
  {
    id: "electromagnetics_skin_effect_busbar",
    slug: "concept-electromagnetics-skin-effect-conductor",
    title: "Skin Effect in an AC Conductor",
    prompt: "A power engineer notices that a solid round copper bar carrying high-frequency AC has a much higher effective resistance than its DC resistance, even though the metal and cross-section are unchanged.",
    discipline: "ELECTRICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["electromagnetics", "conceptual"],
    skillAreas: ["electromagnetics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain the physical mechanism of the skin effect and how skin depth (delta = sqrt(2/(omega*mu*sigma))) sets the effective current-carrying area.", rubric: "Should explain that AC current creates a time-varying internal magnetic field; by Faraday/Lenz this induces eddy currents that oppose current flow most strongly at the center and reinforce it near the surface, pushing current toward the outer skin. Current density falls off roughly exponentially inward with characteristic length delta. As frequency rises, delta shrinks (delta scales as 1/sqrt(f)), so current crowds into a thin annulus, reducing the effective area and raising AC resistance (R_ac roughly inversely proportional to the conducting area, so it rises with sqrt(f) at high f). Higher mu or sigma also reduces delta. Key insight: the conductor's own induced fields expel current from its interior, so only a surface layer of thickness about delta carries useful current at high frequency.", },
      { prompt: "Now the engineer must carry the same high-frequency current with low loss. Compare using a single solid bar, a hollow tube of the same outer diameter, and Litz wire, and justify which to pick.", rubric: "Should reason that because current rides on the surface, the solid bar's core is wasted copper. A hollow tube of the same outer diameter carries nearly the same current with much less metal, so it is far more material-efficient with little resistance penalty (the missing core barely conducts anyway). Litz wire uses many thin insulated strands each thinner than delta, transposed so each strand spends equal time at inside/outside positions; this restores near-full use of the copper and also fights proximity effect, best at moderate frequencies; at very high frequency strand and insulation overhead and proximity effects limit it. Tradeoffs: tube is simple and good for very high f and large currents; Litz is best where strands stay below delta. Key insight: once current is confined to the skin, the winning strategy is to maximize surface area per unit copper, which is exactly what tubes and Litz wire do.", },
    ],
  },
  {
    id: "electromagnetics_tline_reflection_match",
    slug: "concept-electromagnetics-transmission-line-matching",
    title: "Reflections on a Mismatched Line",
    prompt: "A fast digital driver feeds a 50 ohm transmission line that terminates in a high-impedance receiver input. The captured waveform at the receiver shows overshoot followed by stair-step ringing.",
    discipline: "ELECTRICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["electromagnetics", "conceptual"],
    skillAreas: ["electromagnetics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain why the ringing occurs in terms of impedance mismatch and the reflection coefficient (Gamma = (ZL - Z0)/(ZL + Z0)), and why this matters only when the line is electrically long relative to the edge.", rubric: "Should explain that when a wave reaches a load whose impedance ZL differs from the line Z0, part of the wave reflects with coefficient Gamma. A high-Z receiver gives Gamma near +1, so the incident step nearly doubles (overshoot) and a reflection travels back to the source. If the source is also mismatched it re-reflects (source Gamma), bouncing back and forth; each round trip is attenuated/changed, producing the stair-step ringing settling toward final value. This only matters when propagation delay (line length) is significant compared to the signal rise time (rule of thumb: treat as a transmission line when round-trip delay exceeds roughly the edge time, e.g. length > tr*v/2); for very short lines reflections return within the edge and are invisible. Key insight: ringing is multiple reflections bouncing between mismatched ends, and it only appears when the line is electrically long compared with the edge rate.", },
      { prompt: "Now you must eliminate the ringing. Contrast series (source) termination with parallel (end) termination, including how each sets impedance and their power and signal-integrity tradeoffs.", rubric: "Should contrast: Series termination puts a resistor at the driver so R_series + Z_driver equals Z0; the launched edge is a half-amplitude step that doubles at the open-ended high-Z receiver to full value, and the reflection returning to the matched source is absorbed (source Gamma near 0). Pros: near-zero static power, good for point-to-point; cons: only valid at the far end (mid-line taps see the half-step), and adds a small RC-like delay. Parallel/end termination places a resistor equal to Z0 at the receiver so ZL equals Z0 and Gamma near 0, absorbing the wave immediately; pros: clean for multidrop/buses and any tap; cons: continuous DC power and loads the driver (Thevenin or AC-coupled variants reduce DC power). Choice depends on topology, power budget, and whether intermediate nodes must be valid. Key insight: you stop reflections by matching impedance at an end, either making the source impedance equal Z0 (series) or the load equal Z0 (parallel), each with distinct power and topology tradeoffs.", },
    ],
  },
  {
    id: "electromagnetics_capacitor_dielectric_meaning",
    slug: "concept-electromagnetics-capacitance-physical-meaning",
    title: "What Capacitance Physically Means",
    prompt: "A junior engineer treats a capacitor as just a number in a formula. You want them to understand what capacitance physically represents in a parallel-plate structure (C = epsilon*A/d).",
    discipline: "ELECTRICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["electromagnetics", "conceptual"],
    skillAreas: ["electromagnetics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain the physical meaning of capacitance and why C = epsilon*A/d, including where the energy is stored and the role of the dielectric.", rubric: "Should explain capacitance is charge stored per unit voltage (C = Q/V), a measure of how much charge a structure holds for a given potential difference. For parallel plates, larger area A holds more charge at the same field; smaller gap d means the same charge produces a smaller voltage (V = E*d) so C rises; permittivity epsilon captures how the dielectric polarizes to partially cancel the field, letting more charge be stored at the same voltage (relative permittivity > 1 increases C). Energy is stored in the electric field in the gap (energy density = 0.5*epsilon*E^2), not on the plates themselves. Key insight: capacitance measures charge-storage ability per volt, and it grows with area and permittivity and shrinks with gap because all three control how much field/charge a given voltage produces.", },
      { prompt: "Now the engineer doubles the plate area but also slides a grounded conductive sheet partway between the plates. Explain qualitatively how capacitance and the field change and why intuition from the simple formula can mislead here.", rubric: "Should reason that doubling area alone would double C, but inserting a grounded conductor between the plates fundamentally changes the geometry: it effectively splits the structure into two capacitors in series (top plate to sheet, sheet to bottom plate) for the covered region, and the grounded sheet also diverts field lines and can short part of the structure, so the simple single-gap C = epsilon*A/d no longer applies. The grounded sheet terminates field lines, reducing the direct plate-to-plate field in the covered area; the result must be analyzed as a series/parallel combination of partial capacitances. Intuition fails because the formula assumes a single uniform field region between two electrodes; introducing a third grounded electrode breaks that assumption. Key insight: the parallel-plate formula is a special-geometry result, and adding extra conductors changes the field topology so you must decompose the structure into series/parallel capacitances rather than scaling one number.", },
    ],
  },
  {
    id: "electromagnetics_shielding_enclosure_aperture",
    slug: "concept-electromagnetics-shielding-enclosure",
    title: "Shielding a Noisy Enclosure",
    prompt: "A sensitive RF receiver is placed inside a metal enclosure to protect it from external interference. The enclosure has a row of ventilation slots and a seam where the lid bolts on.",
    discipline: "ELECTRICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["electromagnetics", "conceptual"],
    skillAreas: ["electromagnetics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain how a conductive enclosure shields against external fields, distinguishing the mechanisms for low-frequency magnetic fields versus high-frequency electromagnetic fields.", rubric: "Should distinguish: For high-frequency E-fields and plane waves, shielding works by reflection at the conductor surface (large impedance mismatch between free space and the metal) plus absorption inside the wall (fields decay over skin depth), so thin good conductors block high-frequency fields well (shielding effectiveness = reflection loss + absorption loss). For low-frequency magnetic fields, reflection is poor because the wave impedance is low and matches the conductor better; shielding instead relies on induced eddy currents (which need conductivity and thickness) and, at very low frequency, on high-permeability material to divert/redirect flux (magnetic shunting), since absorption over skin depth is weak when delta is large. Key insight: electric and high-frequency fields are blocked mainly by reflection and skin-depth absorption, while low-frequency magnetic fields require eddy currents or high-mu flux diversion, which is why low-frequency magnetic shielding is hard.", },
      { prompt: "Now identify why the vent slots and the bolted seam can wreck the shielding even though the metal walls are intact, and how to fix them.", rubric: "Should explain that shielding integrity depends on uninterrupted surface currents flowing around the enclosure; any slot or gap interrupts these currents and acts as a slot antenna that leaks (and radiates) energy. Leakage is governed by the largest linear dimension of the aperture relative to wavelength, not its area: a long thin slot leaks badly when its length approaches lambda/2, regardless of how narrow it is. A bolted seam with widely spaced bolts behaves as a series of slots between contact points. Fixes: keep aperture maximum dimension well below lambda/20 of the highest frequency; replace one large slot with many small holes (honeycomb vent / waveguide-below-cutoff vents); use conductive EMI gaskets and closely spaced fasteners or continuous contact on the seam to maintain current continuity. Key insight: a shield is only as good as the continuity of its surface currents, so the longest aperture dimension, not wall thickness, often sets the real shielding effectiveness.", },
    ],
  },
];
