import type { PracticeProblem } from "../types";

export const problems: PracticeProblem[] = [
  {
    id: "digital_logic_comb_vs_seq_vending",
    slug: "concept-digital-logic-comb-vs-seq-vending",
    title: "Does This Block Need Memory?",
    prompt: "You are designing the control logic for a vending machine. One block must light a 'change due' LED whenever the coins inserted so far exceed the item price. A teammate sketches it as a purely combinational comparator fed by the live coin sensors.",
    discipline: "COMPUTER",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["digital-logic", "conceptual"],
    skillAreas: ["digital-logic"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain the difference between combinational and sequential logic, and decide whether 'coins inserted so far exceed price' can really be implemented as a purely combinational function of the current sensor inputs. Justify your answer.", rubric: "Should define combinational logic as output that depends only on the present inputs (no memory, no state), versus sequential logic whose output depends on present inputs plus stored past history (state held in flip-flops/registers). Should recognize that 'coins inserted SO FAR' is an accumulated running total, which is by definition state that persists across coin-insertion events. A momentary coin sensor pulse does not encode the total; you must add and store. Therefore it cannot be purely combinational; it needs a register/accumulator (sequential). A pure comparator on instantaneous sensor lines would forget previous coins. Key insight: any requirement involving history, accumulation, or 'so far' implies state, which forces a sequential (registered) implementation rather than combinational logic.", },
      { prompt: "Part 2: Now the spec changes: the machine must also remember whether the correct change was already dispensed for the current transaction, and reset that memory only when a new item is selected. How does this change the state your design must hold, and how would you structure the logic so the 'change due' and 'change dispensed' behaviors do not interfere?", rubric: "Should recognize this adds a second piece of state (a 'dispensed' flag / status bit) on top of the running coin total, pushing the design toward a small finite state machine (e.g., states like IDLE, COLLECTING, CHANGE_DUE, DISPENSED). Should describe holding the accumulator plus a flag, with the flag set when change is dispensed and cleared (reset) on a new item-selection event. Should separate the combinational next-state/output logic from the registered state, and ensure the comparator output is gated by the dispensed flag so it does not re-trigger dispensing. Key insight: each independent thing the system must remember is another state element; clean sequential design separates registered state from combinational next-state/output logic and uses explicit reset conditions to bound each transaction.", },
    ],
  },
  {
    id: "digital_logic_setup_hold_capture",
    slug: "concept-digital-logic-setup-hold-capture",
    title: "When the Flip-Flop Misses the Data",
    prompt: "A data signal drives the D input of an edge-triggered flip-flop clocked at 200 MHz. Intermittently, the captured value is wrong, and the failures get worse when the chip heats up.",
    discipline: "COMPUTER",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["digital-logic", "conceptual"],
    skillAreas: ["digital-logic"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain what setup time and hold time mean for this flip-flop, and describe the chain of events when a setup-time violation occurs. Why might warming the chip make the problem worse?", rubric: "Should define setup time as the minimum interval BEFORE the active clock edge during which D must be stable, and hold time as the minimum interval AFTER the edge during which D must remain stable. A setup violation means D was still changing too close to the edge, so the flop may latch a wrong or indeterminate value, possibly entering metastability (output hovering between valid 0 and 1 before resolving). The available time for combinational logic to settle is roughly Tclk - tsetup - tcq - skew; at 200 MHz the period is 5 ns, leaving little margin. Heating increases gate/wire propagation delay, so combinational paths arrive later and erode the setup margin, turning marginal paths into violations. Key insight: correct capture requires D stable across the setup/hold window around the edge; timing margin shrinks with higher frequency and increases with temperature-induced delay, so a marginal design fails when it gets hot.", },
      { prompt: "Part 2: Now suppose the offending signal is asynchronous - it comes from a different clock domain entirely. Why does this make metastability fundamentally unavoidable on a single flop, and what is the standard technique to make the failure probability acceptably low?", rubric: "Should explain that for a truly asynchronous input there is no fixed phase relationship to the capturing clock, so eventually an edge will land inside the setup/hold window no matter what; you cannot timing-close your way out of it, only reduce the probability. The single flop can go metastable and resolve to an unpredictable value at an unpredictable time. The standard fix is a synchronizer: two (or more) flip-flops in series in the destination clock domain, giving the first flop most of a clock cycle to resolve any metastability before the second flop samples it. This makes mean-time-between-failure (MTBF) exponentially large but never infinite; more stages or slower clock further improve MTBF. Should note only single-bit signals cross this way safely; multi-bit buses need handshakes/FIFOs/gray-code. Key insight: crossing clock domains makes metastability a statistical certainty, so the goal shifts from prevention to making MTBF astronomically large via a multi-flop synchronizer.", },
    ],
  },
  {
    id: "digital_logic_clock_skew_pipeline",
    slug: "concept-digital-logic-clock-skew-pipeline",
    title: "When Skew Helps and When It Hurts",
    prompt: "Two flip-flops sit back to back: FF1 feeds combinational logic that feeds FF2. The clock reaches FF2 slightly later than it reaches FF1 because of routing differences in the clock tree.",
    discipline: "COMPUTER",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["digital-logic", "conceptual"],
    skillAreas: ["digital-logic"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Define clock skew, and explain how this particular skew (clock arriving later at FF2 than at FF1) affects the setup-time and hold-time margins on the path from FF1 to FF2. Use the timing relationships to support your answer.", rubric: "Should define clock skew as the difference in arrival time of the same clock edge at different flip-flops. Let skew = t(FF2 clk) - t(FF1 clk) > 0 here. The setup constraint is roughly Tclk + skew >= tcq + tcomb + tsetup, so positive skew (later clock at the capturing flop) ADDS to the effective period and RELAXES setup on this path. The hold constraint is roughly tcq + tcomb_min >= thold + skew, so positive skew makes hold HARDER (eats into hold margin) because FF2's edge comes later relative to when new data could arrive. Should articulate the tradeoff: skew that helps setup on a path hurts hold on that same path. Key insight: clock skew shifts timing margin between setup and hold; late capture-clock borrows time for setup but spends it from hold, so skew is a double-edged sword that must be budgeted, not ignored.", },
      { prompt: "Part 2: Now consider the reverse path in a feedback loop where FF2 also feeds back through logic into FF1. The skew that relaxed setup on the forward path now applies with the opposite sign on this reverse path. Explain why hold violations are especially dangerous compared to setup violations, and why you cannot simply slow the clock to fix them.", rubric: "Should reason that on the reverse path the same physical skew has opposite sign (capturing flop FF1 now receives the EARLIER clock), which tightens setup there and/or worsens hold elsewhere - showing skew tradeoffs are global, not per-path. Should explain that a hold violation occurs when new data races through fast combinational logic and corrupts the captured value within the hold window; crucially, hold violations are independent of clock PERIOD (they depend on tcq + tcomb_min vs thold + skew), so slowing the clock does NOT fix them - only adding delay (buffers) to fast paths or fixing skew does. Setup violations, by contrast, can always be cured by slowing the clock. Hold failures therefore can survive into silicon and are catastrophic because the chip fails at every frequency. Key insight: setup violations are fixable by lowering frequency, but hold violations are frequency-independent min-delay races; they must be fixed structurally (padding short paths, balancing the clock tree) and are far more dangerous.", },
    ],
  },
  {
    id: "digital_logic_pipelining_throughput",
    slug: "concept-digital-logic-pipelining-throughput",
    title: "Cutting the Long Path in Half",
    prompt: "A combinational datapath performs a multiply followed by an add, all between two registers, and the longest path through it takes 8 ns, capping the clock at about 125 MHz. A reviewer suggests inserting a pipeline register between the multiplier and the adder.",
    discipline: "COMPUTER",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["digital-logic", "conceptual"],
    skillAreas: ["digital-logic"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain why inserting a pipeline register can raise the clock frequency, and distinguish what improves (throughput) from what does not improve, or even worsens (latency for a single result). Use the path delays to reason about the new clock period.", rubric: "Should explain that the maximum clock frequency is set by the longest combinational (critical) path between registers, since Tclk >= tcq + tcomb + tsetup. Inserting a register splits the 8 ns path into two shorter stages (say multiply ~5 ns, add ~3 ns); the new period is governed by the LONGER stage plus register overhead, so roughly Tclk >= 5 ns + overhead, allowing a faster clock (toward ~200 MHz). Should distinguish throughput (results per second) which rises because the faster clock retires a result every cycle in steady state, from latency for one item which does NOT improve and actually gets slightly WORSE: a single result now takes 2 cycles plus the extra register's tcq/tsetup overhead. Key insight: pipelining increases throughput by shortening the critical path, but it does not reduce single-item latency - it trades a small latency penalty (and extra registers/area) for higher sustained throughput.", },
      { prompt: "Part 2: Now suppose the multiply stage alone takes 7 ns and the add takes only 1 ns. The pipeline is badly unbalanced. Explain why this limits the benefit, and what you would do to get closer to the ideal 2x speedup from two stages.", rubric: "Should recognize that pipeline clock speed is dictated by the SLOWEST stage, so a 7 ns multiply stage caps the period near 7 ns + overhead - barely better than the original 8 ns despite paying for an extra register. The 1 ns add stage wastes most of its cycle (idle slack). Should propose rebalancing: split the heavy multiplier across more stages (e.g., partial-product stages or a multi-cycle/staged multiplier) so each stage is closer to ~4 ns, or merge the cheap add into a fuller stage. Going to more, evenly balanced stages moves throughput toward the ideal. Should note the practical limits: register overhead (tcq + tsetup + skew) sets a floor on how finely you can pipeline, and deeper pipelines add latency and hazard/control complexity. Key insight: pipeline throughput is limited by the slowest stage, so the win comes from BALANCING stage delays, not merely from adding registers; an unbalanced split squanders the opportunity while still paying its cost.", },
    ],
  },
  {
    id: "digital_logic_hazard_glitch_decoder",
    slug: "concept-digital-logic-hazard-glitch-decoder",
    title: "The Glitch That Triggered a Reset",
    prompt: "A combinational decoder's output is wired directly to the asynchronous reset of a counter. Most of the time it works, but occasionally the counter resets for no apparent reason, only when certain input bits change simultaneously.",
    discipline: "COMPUTER",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["digital-logic", "conceptual"],
    skillAreas: ["digital-logic"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain what a combinational hazard (glitch) is, why it can appear even when the logic is functionally correct, and why feeding a glitchy combinational signal into an asynchronous reset is dangerous.", rubric: "Should define a hazard/glitch as a transient, unwanted output pulse that occurs while inputs are switching, caused by unequal propagation delays along different paths converging on the output gate. A static-1 hazard is a momentary dip to 0 on a signal that should stay 1 (static-0 the reverse); these happen even though the steady-state truth table is correct, because the circuit passes through a transient term. This is especially likely when multiple input bits change near-simultaneously and one path is slower than another. Feeding such a signal into an asynchronous reset (or any edge/level-sensitive control like a clock or latch enable) is dangerous because async inputs respond to the transient itself, not just the settled value, so a sub-nanosecond glitch can spuriously reset the counter. Key insight: glitches are timing artifacts of differing path delays, harmless on signals only sampled after they settle, but hazardous on asynchronous control inputs that react to the transient.", },
      { prompt: "Part 2: Now the constraint is that this reset signal really must be derived from decoded logic. Describe how to make the design robust - both the general synchronous-design principle that avoids this whole class of bug, and any narrower fix if the asynchronous behavior cannot be removed.", rubric: "Should give the synchronous-design principle: do not drive asynchronous control (resets, clocks, enables) with raw combinational outputs; instead register the decoded signal (sample it with a flip-flop on a clock edge) so it is only observed AFTER it has settled, making glitches invisible. Equivalently, convert the async reset to a SYNCHRONOUS reset gated by the clock so transients between edges are ignored. Should note glitches are sampled away because the flop only looks at the value at the clock edge, by which time the combinational logic has settled. Narrower fixes if async is unavoidable: redesign the logic to be hazard-free by adding redundant (consensus) prime-implicant terms that cover the transition, glitch-filtering, or restructuring so only one input changes at a time (one-hot/Gray-coded inputs). Key insight: the durable cure is synchronous design - register combinational outputs so glitches never reach sensitive inputs; hazard-free Boolean redesign (consensus terms) is the fallback only when the asynchronous path cannot be removed.", },
    ],
  },
  {
    id: "digital_logic_ff_latch_timing",
    slug: "concept-digital-logic-ff-latch-timing",
    title: "Latch or Flip-Flop, and Why It Matters",
    prompt: "A junior engineer's HDL accidentally synthesized a transparent (level-sensitive) latch where an edge-triggered flip-flop was intended. In simulation everything looked fine, but the silicon fails timing checks and behaves unpredictably in the lab.",
    discipline: "COMPUTER",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["digital-logic", "conceptual"],
    skillAreas: ["digital-logic"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain the functional difference between a level-sensitive latch and an edge-triggered flip-flop, and why an unintended latch is troublesome in a synchronous design that assumes flip-flops everywhere.", rubric: "Should explain that a level-sensitive (transparent) latch passes its input through to the output the entire time the enable/clock level is asserted (transparent during the active level, holds when deasserted), whereas an edge-triggered flip-flop samples and updates its output only at the active clock EDGE and holds otherwise. Because a latch is transparent for a whole half-cycle, data can ripple through it during that window, breaking the synchronous assumption that every storage element updates once per clock edge in lockstep. This complicates static timing analysis (time-borrowing across the transparent window), can let glitches or fast paths propagate, and may create unintended combinational feedback. Should note simulation with an idealized clock can hide the problem while real delays expose it. Key insight: a flip-flop samples at an edge and is opaque between edges; a latch is transparent during a level, so an accidental latch violates the one-update-per-edge discipline that synchronous timing analysis depends on.", },
      { prompt: "Part 2: Now suppose the design is intentionally built from a master-slave pair of latches. Explain how two level-sensitive latches combine to behave like a single edge-triggered flip-flop, and what role the non-overlapping or inverted clock phases play.", rubric: "Should explain that a master-slave flip-flop chains two latches with opposite clock polarity (master enabled on one clock level, slave on the other). When the clock is low, the master is transparent and tracks D while the slave holds; when the clock goes high, the master becomes opaque (latching the value present just before the edge) and the slave becomes transparent, passing that captured value to the output. The net effect is that the output updates only around the clock transition - effectively edge-triggered behavior - because at no single instant are both latches simultaneously transparent from input to output. The non-overlapping or inverted phases are essential: if both latches were transparent at once, data could race straight through (a transparency path), destroying the edge behavior and causing hold-time failures. Key insight: an edge-triggered flip-flop is two oppositely-clocked transparent latches in series; the opposing/non-overlapping phases guarantee only one is transparent at a time, so new data is captured at the edge and cannot race through.", },
    ],
  },
];
