import type { PracticeProblem } from "../types";

export const problems: PracticeProblem[] = [
  {
    id: "materials_stress_strain_read",
    slug: "concept-materials-reading-stress-strain",
    title: "Reading Two Tensile Curves",
    prompt: "You are evaluating two candidate alloys for a structural bracket. On a single stress-strain plot, Alloy A has a high yield point but fractures shortly after with almost no necking. Alloy B yields at a lower stress but climbs to a slightly higher ultimate stress, then necks visibly before fracture at large strain.",
    discipline: "MECHANICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["materials", "conceptual"],
    skillAreas: ["materials"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Walk me through what each region of these curves tells you about the two alloys, and which one you would call tougher and why. Be precise about the difference between strength and toughness here.", rubric: "Identifies elastic region (slope = Young's modulus, recoverable), yield point (onset of plastic flow), strain hardening up to ultimate tensile stress, then necking and fracture. States that toughness is the AREA under the stress-strain curve (energy absorbed to failure), so Alloy B is tougher despite Alloy A having higher yield strength. Notes Alloy A is strong but brittle/low ductility (little plastic strain, no necking); Alloy B is more ductile. Connects necking to onset of localized plastic instability past UTS. Key insight: strength is a stress value on the curve while toughness is the energy (area) under it, so a stronger material can be far less tough." },
      { prompt: "Part 2: Now the bracket may see occasional impact/shock loads and the design team says 'just pick the strongest one.' Do you still agree, and what specifically would you ask to measure before committing?", rubric: "Pushes back on 'strongest = best' for impact: under shock loading the ability to absorb energy and tolerate flaws matters more than peak strength, so the tougher/more ductile Alloy B is likely safer. Notes a high-strength low-ductility material can fail catastrophically with little warning. Asks for impact toughness data (Charpy/Izod), fracture toughness (K_IC), behavior at service temperature (ductile-to-brittle transition for BCC metals), and strain-rate sensitivity. Mentions a safety margin / leak-before-break or graceful-failure reasoning. Key insight: for impact and flaw tolerance the relevant property is energy absorption and fracture toughness, not the yield or ultimate strength alone." },
    ],
  },
  {
    id: "materials_work_hardening",
    slug: "concept-materials-cold-work-and-anneal",
    title: "Cold-Worked Wire That Cracks on Bending",
    prompt: "A copper wire is drawn down to a smaller diameter through several cold-drawing passes. After the final pass it is much stronger and harder than the starting stock, but when a technician tries to coil it tightly it cracks instead of bending smoothly.",
    discipline: "MECHANICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["materials", "conceptual"],
    skillAreas: ["materials"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain at the microstructural level why cold drawing made the wire stronger and harder but also caused it to crack when coiled. Use dislocation behavior in your reasoning.", rubric: "Explains work (strain) hardening: plastic deformation multiplies dislocations; the increased dislocation density means dislocations tangle and impede each other, raising the stress needed for further slip (Taylor hardening). Result is higher yield/hardness but reduced remaining ductility because much of the available plastic capacity has been consumed and the structure is heavily strained. Cracking on coiling = the heavily cold-worked wire has little ductility left, so added bending strain exceeds its low fracture strain. Key insight: cold work raises strength by raising dislocation density, but it trades away ductility, so a work-hardened part has little plastic reserve left for additional forming." },
      { prompt: "Part 2: Now suppose the wire must still be coiled tightly in service but the customer also wants it as strong as possible afterward. What process would you insert and how would you control it to balance both goals?", rubric: "Proposes annealing (recovery, recrystallization, possibly grain growth) to restore ductility before or between forming steps. Describes recovery (rearrangement/annihilation of dislocations, relieves stress, small property change), recrystallization (new strain-free grains nucleate and grow, large drop in strength and recovery of ductility), and grain growth (coarsening that further softens). Controls via temperature and time, and limits grain growth to avoid going too soft/coarse. To keep strength high, anneal to restore formability, coil, then optionally do a final light cold work or stop at partial recrystallization; or use a fine grain size for Hall-Petch strengthening. Key insight: annealing reverses work hardening by replacing the dislocated structure with new grains, and stopping it at the right point lets you coil the wire yet retain useful strength." },
    ],
  },
  {
    id: "materials_fatigue_sn",
    slug: "concept-materials-fatigue-below-yield",
    title: "Shaft That Fails Below Yield",
    prompt: "A rotating steel shaft has been in service for two years carrying cyclic bending loads. The peak stress in service is well below the material yield strength, yet the shaft fractures. The fracture surface shows a smooth region with curved beach marks leading to a final rough zone.",
    discipline: "MECHANICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["materials", "conceptual"],
    skillAreas: ["materials"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Why did this shaft fail even though the stress never reached yield? Explain the failure mechanism and what the fracture surface features tell you, and describe what an S-N curve would predict.", rubric: "Identifies fatigue failure: repeated cyclic loading initiates a crack (often at a surface defect or stress concentration), which grows incrementally each cycle (beach marks = arrest/progression markings of crack front) until the remaining cross-section can no longer carry the load and fails fast (rough final-fracture zone). Stress below yield still drives fatigue because local plastic strain at the crack tip and stress risers accumulate damage cycle by cycle. S-N curve relates stress amplitude S to cycles-to-failure N: higher amplitude means fewer cycles; for steels there is often an endurance/fatigue limit below which life is effectively infinite. Key insight: fatigue is progressive crack growth under cyclic load, so a part can fail far below its static yield strength given enough cycles." },
      { prompt: "Part 2: Now the redesign must guarantee effectively infinite life and you cannot change the material. What specific changes to geometry, surface, and loading would you make, and which one matters most?", rubric: "Aims to keep service stress amplitude below the steel fatigue/endurance limit. Reduce stress concentrations: larger fillet radii, remove sharp corners/notches/keyway stress risers, better surface finish (fatigue cracks usually start at the surface). Introduce compressive residual surface stress via shot peening, rolling, carburizing/nitriding to suppress crack initiation. Lower the mean and amplitude of stress (larger diameter to drop bending stress, reduce misalignment, lower the load), and consider that aluminum has no true endurance limit but steel does. Notes most fatigue cracks initiate at the surface so surface condition/residual stress and eliminating notches usually matter most. Key insight: infinite life means keeping the cyclic stress under the endurance limit, and the highest-leverage moves attack crack INITIATION at the surface and at stress concentrations." },
    ],
  },
  {
    id: "materials_creep_turbine",
    slug: "concept-materials-creep-turbine-blade",
    title: "Turbine Blade Stretching in Service",
    prompt: "A gas turbine blade runs at high temperature under a steady centrifugal (tensile) load. Over thousands of hours engineers find the blades have slowly elongated, even though the stress is constant and well below the yield strength at room temperature.",
    discipline: "MECHANICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["materials", "conceptual"],
    skillAreas: ["materials"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain the mechanism causing this slow, time-dependent elongation, why temperature is essential to it, and sketch in words the three stages of the strain-versus-time response.", rubric: "Identifies creep: time-dependent plastic deformation under constant stress, significant at high homologous temperature (typically above ~0.3 to 0.4 of the absolute melting temperature). Mechanisms are thermally activated: dislocation climb/glide and diffusional flow (Nabarro-Herring/Coble grain-boundary diffusion); temperature provides the atomic mobility (diffusion) that lets atoms/dislocations rearrange over time. Three stages: primary (decelerating strain rate as hardening dominates), secondary/steady-state (roughly constant minimum strain rate, design-relevant), tertiary (accelerating rate as voids/necking accumulate leading to rupture). Notes stress below room-temperature yield still creeps because the process is diffusion- and time-driven, not instantaneous yield. Key insight: creep is diffusion-assisted time-dependent flow, so a constant sub-yield stress at high temperature still produces permanent elongation given enough time." },
      { prompt: "Part 2: Now you must extend blade life at the same temperature and load. What material/microstructural and design strategies would you use, and explain why grain structure matters in the opposite direction from low-temperature design?", rubric: "Strategies: use superalloys with high melting point, solid-solution and gamma-prime precipitate strengthening, and slow-diffusing refractory alloying. Critically, COARSEN grains or eliminate grain boundaries: directionally solidified or single-crystal blades reduce grain-boundary sliding and diffusional (Coble) creep, the opposite of low-temperature design where fine grains strengthen via Hall-Petch. Add thermal barrier coatings and internal cooling to lower the metal temperature (creep is exponentially temperature sensitive). Reduce stress (geometry/mass), and use the Larson-Miller parameter to trade temperature, time, and stress for life prediction. Key insight: because grain boundaries are fast diffusion/sliding paths at high temperature, creep resistance favors few or no grain boundaries (single crystal), which is the reverse of fine-grain strengthening used at low temperature." },
    ],
  },
  {
    id: "materials_fracture_toughness",
    slug: "concept-materials-flaw-tolerance-tradeoff",
    title: "Strong but Crack-Sensitive Pressure Vessel",
    prompt: "Two steels are proposed for a pressure vessel. Steel X has very high yield strength; Steel Y is somewhat lower strength but has much higher fracture toughness (K_IC). Inspection can reliably detect cracks down to a certain minimum size, but not smaller.",
    discipline: "MECHANICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["materials", "conceptual"],
    skillAreas: ["materials"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Using fracture-mechanics reasoning, explain why the higher-strength steel may actually be the riskier choice for this vessel. Bring in the relationship between stress, flaw size, and toughness.", rubric: "Uses fracture mechanics: a pre-existing crack fails when the stress intensity K = Y*sigma*sqrt(pi*a) reaches the material fracture toughness K_IC. Rearranged, the critical (tolerable) flaw size a_c scales with (K_IC/sigma)^2. A high-strength steel is typically run at higher design stress AND tends to have lower toughness, so its critical flaw size can be very small, possibly smaller than what inspection can detect, meaning an undetectable crack could propagate catastrophically. Steel Y with higher K_IC tolerates larger flaws before unstable fracture. Discusses the general strength-toughness tradeoff. Key insight: failure is governed by K_IC versus stress and flaw size, so a stronger but lower-toughness steel can have a critical flaw smaller than your inspection limit, making it less safe despite higher strength." },
      { prompt: "Part 2: Now management mandates Steel X for its strength. What design philosophy and concrete safeguards would you impose so the vessel can still be certified safe, and what is the failure mode you are most trying to avoid?", rubric: "Adopt a damage-tolerant / leak-before-break philosophy: ensure the critical through-wall crack length exceeds the wall thickness so a flaw leaks (detectable) before it goes unstable and bursts. Lower the operating stress (thicker wall, lower pressure) to enlarge the critical flaw size back above the inspection detection limit. Impose tighter NDE/inspection intervals and improved detection capability, proof testing, and tracking subcritical growth (fatigue/stress-corrosion crack growth) over time. Control environment and temperature to stay above any ductile-to-brittle transition. Most-feared mode: sudden brittle/unstable fast fracture (catastrophic rupture) rather than slow detectable leakage. Key insight: if you must use the strong low-toughness steel, you engineer around it by lowering stress and using leak-before-break plus inspection so the critical flaw stays larger than what you can reliably detect, converting a catastrophic burst into a detectable leak." },
    ],
  },
  {
    id: "materials_ddt_pipeline",
    slug: "concept-materials-ductile-brittle-transition",
    title: "Pipeline Brittle in Winter",
    prompt: "A carbon-steel (BCC) pipeline performs fine all summer. During a cold winter snap, a section fractures suddenly with a flat, faceted fracture surface and almost no plastic deformation, despite seeing the same pressure it always had.",
    discipline: "MECHANICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["materials", "conceptual"],
    skillAreas: ["materials"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain why temperature alone turned a normally ductile steel into one that fails in a brittle, low-energy way, and why the crystal structure of the steel is central to this behavior.", rubric: "Identifies the ductile-to-brittle transition temperature (DBTT): below it, the steel absorbs little impact energy and fails by brittle (cleavage, flat/faceted) fracture; above it, it fails ductile with plastic deformation. BCC metals (like carbon steel) show a pronounced DBTT because the stress to move dislocations (Peierls stress) rises sharply as temperature drops, so plastic flow is suppressed and cleavage wins; FCC metals (e.g. austenitic stainless, aluminum) generally lack a sharp DBTT and stay ductile cold. The cold snap dropped the metal below its DBTT. Flat low-energy surface = cleavage/brittle fracture. Key insight: in BCC steels the yield/flow stress is strongly temperature dependent, so below the DBTT dislocation motion is choked off and the steel cleaves in a brittle manner even at normal service stress." },
      { prompt: "Part 2: Now you must specify a replacement steel that will not do this, and the line runs even colder at a remote site. What material and microstructural levers lower the DBTT, and what quick test would you require on incoming material?", rubric: "Levers to lower DBTT / improve cold toughness: refine grain size (finer grains lower DBTT and raise toughness, one of the few changes that helps both strength and toughness), reduce embrittling impurities (low phosphorus/sulfur, control carbon), add nickel (improves low-temperature toughness, can favor more austenite/FCC behavior), use proper heat treatment (normalizing/quench-and-temper for fine tough microstructure), or switch to an FCC austenitic stainless for severe cold. Avoid coarse grains and high carbon. Required acceptance test: Charpy V-notch impact testing at the minimum service temperature to confirm energy absorption / shift the transition curve, ensuring service temperature stays on the upper-shelf side. Key insight: lowering the DBTT below the coldest service temperature is the goal, and grain refinement plus clean chemistry plus nickel achieve it, verified by Charpy impact tests at service temperature." },
    ],
  },
];
