import type { PracticeProblem } from "../types";

export const problems: PracticeProblem[] = [
  {
    id: "orbital_mechanics_freefall_orbit",
    slug: "concept-orbital-mechanics-freefall-orbit",
    title: "Why an Orbiting Astronaut Floats",
    prompt: "A new hire asks you why astronauts on the International Space Station float, given that the ISS orbits at only about 400 km altitude where Earth's gravity is still roughly 90 percent as strong as at the surface.",
    discipline: "AEROSPACE",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["orbital-mechanics", "conceptual"],
    skillAreas: ["orbital-mechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain in physical terms why the astronauts experience weightlessness even though gravity is nearly as strong as on the ground. What is actually happening to the station and everyone in it?", rubric: "An ideal answer states gravity is NOT absent and is the only significant force acting. The station and astronauts are in continuous freefall: they are accelerating toward Earth at the same local g, but their large tangential velocity (about 7.7 km/s) means the curved surface of Earth falls away beneath them as fast as they fall toward it, so they never get closer. Weightlessness is the absence of a supporting normal force, not the absence of gravity; everything in the station falls together at the same rate so there is no relative acceleration to feel. A good answer may invoke Newton's cannonball thought experiment. Key insight: an orbit is just perpetual freefall with enough sideways speed to keep missing the planet, so gravity is fully present but produces no felt weight." },
      { prompt: "Part 2: Now suppose the station's engines fire to instantly cancel ALL of its orbital (tangential) velocity, leaving it momentarily at rest 400 km up. What do the astronauts feel during the brief period right after, and what happens to the station?", rubric: "An ideal answer recognizes that with zero tangential velocity there is no longer anything keeping them from falling: the station begins a radial plunge straight toward Earth (a degenerate, zero-angular-momentum trajectory). Crucially, the astronauts STILL feel weightless during the fall, because they and the station continue to accelerate together at the same g; weightlessness persists as long as gravity is the only force and everything falls together. Felt weight returns only when a non-gravitational force acts unevenly (atmospheric drag building up, or impact). A strong answer notes the difference from orbit is the lack of tangential speed, not the presence or absence of the floating sensation. Key insight: floating comes from shared freefall, not from being in orbit, so killing the orbital velocity turns a stable orbit into a fatal vertical fall while the sensation of weightlessness is unchanged until drag or impact intervenes." },
    ],
  },
  {
    id: "orbital_mechanics_prograde_burn",
    slug: "concept-orbital-mechanics-prograde-burn",
    title: "Where a Prograde Burn Shows Up",
    prompt: "A spacecraft is in a circular low Earth orbit. The pilot performs a short prograde burn (thrusting in the direction of motion) at a single point and then coasts.",
    discipline: "AEROSPACE",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["orbital-mechanics", "conceptual"],
    skillAreas: ["orbital-mechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: A trainee expects that speeding up at point A will raise the orbit right there at point A. Explain why instead the altitude increases most on the OPPOSITE side of the orbit, and what shape the orbit becomes.", rubric: "An ideal answer explains that adding speed at A increases the orbital energy and converts the circle into an ellipse. Point A becomes the perigee (lowest point) of the new ellipse, and the apogee (highest point) appears half an orbit later on the opposite side. The burn raises the altitude reached half a period downstream, not instantaneously, because the added velocity changes the trajectory the craft then follows; it takes time and the geometry of the conic to carry the craft up to the new high point. A good answer notes the altitude at the burn point itself barely changes (it is now perigee). Conservation of angular momentum and energy along the ellipse explains the slow-down at apogee. Key insight: a burn changes the orbit's shape, and the effect of adding energy at one point manifests as a higher apoapsis 180 degrees away, because the new conic section carries the craft there." },
      { prompt: "Part 2: Now the pilot instead wants to raise the altitude specifically AT point A (make the orbit higher right where the burn happens) while keeping it roughly circular afterward. What burn strategy accomplishes this, and why does a single prograde burn fail to do it?", rubric: "An ideal answer recognizes a single prograde burn at A makes A the perigee, so it cannot raise altitude AT A. To raise altitude at A you must change the orbit half a revolution earlier: burn prograde at the point opposite A so that A becomes the new apogee, raising altitude at A. To then circularize at the higher altitude you perform a second prograde burn when you arrive at the raised apogee. This is exactly a Hohmann-type two-burn sequence. A strong answer ties this back to the rule that you affect the far side: to lift a given location you burn at the antipode and then circularize on arrival. Key insight: because burns raise the opposite side, raising and circularizing a specific point requires a two-burn plan that targets that point as the new apoapsis and then re-circularizes there." },
    ],
  },
  {
    id: "orbital_mechanics_hohmann_efficiency",
    slug: "concept-orbital-mechanics-hohmann-efficiency",
    title: "Hohmann Transfer Tradeoffs",
    prompt: "Mission planning needs to move a satellite from a 400 km circular parking orbit up to a higher 20000 km circular orbit. The baseline plan is a two-burn Hohmann transfer.",
    discipline: "AEROSPACE",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["orbital-mechanics", "conceptual"],
    skillAreas: ["orbital-mechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Walk through the two burns of a Hohmann transfer between these two circular orbits. Where does each burn happen, what direction is it, and why is this maneuver considered fuel-optimal for the two-impulse case?", rubric: "An ideal answer describes burn 1: a prograde burn at the low circular orbit that raises apogee to the target altitude, placing the craft on an elliptical transfer orbit whose perigee is the low orbit and apogee is the high orbit. Then a coast of half the transfer ellipse period to apogee. Burn 2: a second prograde burn at apogee to raise perigee up to the target radius, circularizing at 20000 km. It is optimal among two-impulse coplanar transfers because both burns are tangential (aligned with velocity), which is the most efficient use of impulse for changing orbital energy, and it uses the minimum total delta-v for a two-burn transfer between circular coplanar orbits. Key insight: the Hohmann transfer is a single tangent ellipse kissing both circular orbits, with two prograde burns at perigee and apogee, minimizing two-impulse delta-v by keeping every burn aligned with motion." },
      { prompt: "Part 2: Now the target is changed to an extremely high orbit, far beyond 20000 km. An engineer suggests a bi-elliptic transfer (three burns, going way out past the target then dropping back in) might use LESS total delta-v than a Hohmann. Explain when and why a bi-elliptic transfer can beat a Hohmann, and the practical cost of using it.", rubric: "An ideal answer explains that for large ratios of final-to-initial orbit radius (roughly above about 11.94, and definitely advantageous above ratios near 15), the bi-elliptic transfer can require less total delta-v than the Hohmann. The reason is the Oberth effect and the geometry: by first raising apogee to a very large intermediate radius, the second burn happens where orbital speed is very low, so a small delta-v there produces a large change in perigee; the apogee-raising and final-lowering burns become cheaper than the brute-force second Hohmann burn at moderate ratios. The practical cost is dramatically longer transfer time, since the craft coasts out to a huge intermediate apogee and back, and added operational complexity with three burns. Key insight: bi-elliptic trades time for delta-v, winning only for very large radius ratios because pushing the maneuver out to low-speed regions makes the perigee-raising burn cheap, at the price of a much longer mission." },
    ],
  },
  {
    id: "orbital_mechanics_geostationary",
    slug: "concept-orbital-mechanics-geostationary",
    title: "Designing a Geostationary Slot",
    prompt: "A communications company wants a satellite that appears fixed in the sky above a ground station so its dish never has to move.",
    discipline: "AEROSPACE",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["orbital-mechanics", "conceptual"],
    skillAreas: ["orbital-mechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: State the three orbital conditions a satellite must satisfy to be truly geostationary, and explain physically why each one is required for the satellite to appear motionless from the ground.", rubric: "An ideal answer lists the three conditions: (1) orbital period equal to one sidereal day (about 23 h 56 m), so the satellite's angular rate matches Earth's rotation; this fixes the altitude at about 35786 km (radius about 42164 km) via Kepler's third law since period depends only on semi-major axis. (2) Zero inclination, i.e. the orbit lies in Earth's equatorial plane; otherwise the satellite would trace a north-south figure-eight (analemma) over the day. (3) Zero eccentricity (circular), so the angular speed is constant and matches Earth's uniform rotation; an eccentric orbit speeds up and slows down (varying true anomaly rate), causing east-west drift. A strong answer distinguishes geosynchronous (matching period only) from geostationary (period plus equatorial plus circular). Key insight: appearing motionless requires matching Earth's rotation in rate AND keeping the angular rate constant and in the equatorial plane, which forces a unique altitude, zero inclination, and zero eccentricity." },
      { prompt: "Part 2: Now the customer is at high latitude (say 65 degrees north) and complains the geostationary satellite sits very low on the horizon, often blocked by terrain. What orbit would you propose instead, and what is the fundamental orbital-mechanics reason a geostationary satellite can never appear high overhead at that latitude?", rubric: "An ideal answer explains a geostationary satellite is fixed over the equator, so from 65 degrees north it always appears at a low elevation angle near the southern horizon; this is fundamental because a zero-inclination equatorial orbit can never have its sub-satellite point leave the equator, so high-latitude users see it low. The proposed alternative is a highly elliptical, high-inclination orbit such as a Molniya orbit (inclination near 63.4 degrees to freeze the argument of perigee, period of half a sidereal day, high eccentricity with apogee over the northern hemisphere) or a Tundra orbit (one sidereal day period). The satellite dwells near apogee for many hours at high elevation over the high-latitude region; a constellation of two or three provides continuous coverage. A strong answer notes the 63.4 degree critical inclination zeros the perigee drift (J2 effect) so apogee stays over the north. Key insight: equatorial geostationary geometry physically caps elevation for high-latitude users, so coverage there requires inclined highly elliptical orbits that loiter at apogee over the pole-ward region." },
    ],
  },
  {
    id: "orbital_mechanics_energy_altitude",
    slug: "concept-orbital-mechanics-energy-altitude",
    title: "The Faster-Means-Lower Paradox",
    prompt: "A spacecraft chasing another vehicle in the same circular orbit is behind it and wants to catch up. A trainee says the obvious move is to fire prograde to speed up and close the gap.",
    discipline: "AEROSPACE",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["orbital-mechanics", "conceptual"],
    skillAreas: ["orbital-mechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain why firing prograde to speed up actually causes the chaser to FALL BEHIND the target over time, and what the correct maneuver to catch up is. Address the relationship between orbital speed and altitude.", rubric: "An ideal answer explains that a prograde burn raises the orbit into a larger, higher-energy ellipse with a longer period; by Kepler's third law a higher orbit takes more time per revolution, so the chaser ends up lagging the target. Although the chaser is momentarily faster, its average angular rate drops because it is now in a bigger, slower orbit. The correct move to catch up is a RETROGRADE burn: lowering the orbit puts the chaser in a smaller, shorter-period orbit with a higher angular rate, so it pulls ahead in phase angle; once ahead, it burns prograde to return to the target's orbit. A strong answer notes the counterintuitive inverse relation: in circular orbits, lower altitude means higher orbital speed and shorter period. Key insight: to catch up you slow down (drop to a faster lower orbit) and to fall back you speed up, because orbital energy and period increase with altitude while orbital speed decreases with altitude." },
      { prompt: "Part 2: Now consider the energy bookkeeping. When the chaser does a prograde burn and ends up in a higher orbit, its speed at the new circular altitude is actually LOWER than its original speed, yet you added kinetic energy with the burn. Reconcile this: where did the energy go, and why is orbital speed lower up high?", rubric: "An ideal answer uses the total specific orbital energy, which is the sum of kinetic and gravitational potential energy and equals minus mu over twice the semi-major axis. The prograde burn adds energy, raising the total (making it less negative) and increasing the semi-major axis. However, the increase shows up overwhelmingly as gravitational potential energy (the craft is higher), and potential energy rises more than kinetic, so the circular speed at the higher orbit is actually lower than the original circular speed. Circular orbital speed scales as the square root of mu over r, so larger r means smaller speed. A strong answer notes the virial-like result that in a circular orbit kinetic energy is half the magnitude of potential energy and the total energy is negative; adding energy trades a lot of speed for a lot of altitude. Key insight: the burn raises total orbital energy, but that energy is banked mostly as potential energy at higher altitude, so the steady circular speed up high is lower even though you injected kinetic energy." },
    ],
  },
  {
    id: "orbital_mechanics_gravity_assist",
    slug: "concept-orbital-mechanics-gravity-assist",
    title: "Stealing Speed From a Planet",
    prompt: "An interplanetary probe with a limited fuel budget needs to reach the outer solar system. Mission design proposes a gravity assist (slingshot) flyby of Jupiter to gain speed.",
    discipline: "AEROSPACE",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["orbital-mechanics", "conceptual"],
    skillAreas: ["orbital-mechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: A skeptic argues a gravity assist is impossible because in the planet's own reference frame the probe leaves with exactly the same speed it arrived (energy conserved during the flyby). Explain how the probe nonetheless gains speed relative to the Sun, and where that energy actually comes from.", rubric: "An ideal answer agrees that in the planet's frame the flyby is an elastic hyperbolic encounter: the probe's speed relative to the planet is unchanged in magnitude but its direction is rotated. The gain appears in the Sun (heliocentric) frame because the planet is itself moving around the Sun; adding the rotated planet-relative velocity to the planet's orbital velocity can yield a larger heliocentric speed (when the probe is deflected to come out more aligned with the planet's motion). Energy is conserved overall: the probe's energy gain is taken from the planet's orbital energy, slowing the planet by an utterly negligible amount due to its enormous mass. A strong answer frames it as a momentum exchange between probe and planet mediated by gravity. Key insight: the slingshot works because speed is frame-dependent; the flyby only rotates the planet-relative velocity vector, but vector-adding the planet's heliocentric motion changes Sun-frame speed, with the energy borrowed from the planet's orbit." },
      { prompt: "Part 2: Now suppose the mission instead needs the probe to SLOW DOWN (lose heliocentric speed) so it can drop into the inner solar system toward Mercury. Can a gravity assist accomplish a deceleration, and what changes about the flyby geometry to make that happen?", rubric: "An ideal answer affirms that a gravity assist can decelerate the probe in the heliocentric frame just as it can accelerate it; the direction of the velocity change depends on flyby geometry. To lose heliocentric speed, the probe is routed so that the planet-relative velocity is rotated to come out pointing more AGAINST the planet's orbital motion (a leading-side or trailing-side pass chosen so the outgoing planet-relative velocity opposes the planet's velocity vector), so the vector sum with the planet's orbital velocity is smaller. In this case the probe gives energy to the planet (speeding the planet up negligibly). Real missions to Mercury (e.g. MESSENGER, BepiColombo) use multiple Venus and Mercury flybys precisely to shed heliocentric energy. A strong answer stresses it is the choice of which side of the planet to pass (deflection direction) that flips assist into a brake. Key insight: gravity assists are reversible energy exchanges, so choosing a flyby geometry that rotates the relative velocity to oppose the planet's motion produces deceleration, dumping the probe's energy into the planet's orbit." },
    ],
  },
];
