import type { PracticeProblem } from "../types";

export const problems: PracticeProblem[] = [
  {
    id: "biomechanics_stress_shielding_hip",
    slug: "concept-biomechanics-stress-shielding-hip",
    title: "Bone Loss Around a Hip Stem",
    prompt: "A patient receives a cementless titanium femoral stem for a total hip replacement. Ten years later, follow-up X-rays show the bone in the proximal femur (around the top of the stem) has become noticeably thinner and less dense, while the bone near the stem tip looks fine.",
    discipline: "BIOMEDICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["biomechanics", "conceptual"],
    skillAreas: ["biomechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain mechanically why the proximal bone resorbed. Walk through how the implant changed the load path and why that triggered the bone to remodel.", rubric: "Should identify stress shielding: the stiff metal stem (E roughly 110 GPa for Ti vs roughly 15-20 GPa for cortical bone) carries most of the axial/bending load and bypasses the proximal bone. Strain in the surrounding bone drops below its physiological homeostatic set point. Per Wolff's law / the mechanostat (Frost), bone adapts to strain: low strain triggers net resorption by osteoclasts, so density and cortical thickness fall. Load follows the stiffer parallel path, like a stiff bar in parallel with a compliant one taking the larger share. Key insight: bone is a living material that remodels to maintain a target strain, so a too-stiff implant starves the bone of the mechanical signal it needs to maintain mass." },
      { prompt: "Now the constraints change. A vendor proposes a stem made of a lower-modulus material (for example a porous titanium or a composite stem with E closer to bone). Would this reduce proximal stress shielding, and what new trade-off or risk does lowering the stem stiffness introduce?", rubric: "Should say yes: a lower-modulus stem shares load more evenly, raising proximal bone strain back toward homeostasis and reducing resorption. Trade-offs: a more compliant stem flexes more, increasing micromotion at the bone-implant interface which can impair osseointegration/initial fixation and cause pain or loosening; higher cyclic strain in the stem itself raises fatigue concern; manufacturing/strength limits. The goal is modulus matching while preserving fixation stability and fatigue strength. Key insight: there is a fundamental tension between making an implant compliant enough to load the bone and stiff/strong enough to stay fixed and survive fatigue." },
    ],
  },
  {
    id: "biomechanics_viscoelastic_tissue",
    slug: "concept-biomechanics-viscoelastic-tissue",
    title: "Why Soft Tissue Cares About Speed",
    prompt: "In a lab you pull on a strip of tendon. When you stretch it slowly it feels relatively compliant, but when you yank it quickly it feels much stiffer and resists more. If you hold it at a fixed length, the force you measure slowly drops over a few minutes.",
    discipline: "BIOMEDICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["biomechanics", "conceptual"],
    skillAreas: ["biomechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Name the material behavior on display and explain the two observations (rate-dependent stiffness and the slow force drop at fixed length) in terms of that behavior and the tissue's structure.", rubric: "Should identify viscoelasticity (combined elastic + viscous/time-dependent response). Rate dependence: faster loading gives a higher apparent modulus because the viscous component resists rapid deformation; collagen fibers and the proteoglycan/water matrix do not have time to rearrange or for fluid to redistribute. The slow force drop at constant length is stress relaxation: fibers uncrimp/realign and fluid flows, so internal stress decays over time. Related phenomena: creep (under constant load) and hysteresis (energy loss per cycle). Structural basis: crimped collagen, ground substance, and interstitial fluid. Key insight: soft tissue stiffness is not a single number; it depends on loading rate and time because the tissue is viscoelastic, blending solid-like and fluid-like response." },
      { prompt: "Now the constraints change. Instead of one slow pull, you cyclically load and unload the tendon many times at the same rate before testing it. The first few cycles look different from later cycles, and the loop stabilizes. Explain what is happening and why experimentalists deliberately do this before recording data.", rubric: "Should describe preconditioning: early cycles show progressively lower peak stress / shifting loops as the tissue's internal structure reorganizes (fiber realignment, fluid redistribution, breaking of weak cross-links) until a repeatable steady-state hysteresis loop is reached. Each loop encloses an area = energy dissipated (hysteresis). Experimentalists precondition so that recorded stress-strain data are reproducible and represent the tissue's in-vivo cyclic working state rather than a one-time transient. Key insight: viscoelastic tissue has memory of its recent loading history, so meaningful, repeatable mechanical data require preconditioning to a stable cyclic state." },
    ],
  },
  {
    id: "biomechanics_anisotropy_bone",
    slug: "concept-biomechanics-anisotropy-bone",
    title: "Direction Matters in Bone",
    prompt: "A test lab cores small cylindrical specimens from the shaft of a long bone. Some are cut so the bone's long axis runs along the cylinder, others so the long axis runs across it. Loaded to failure, the along-axis specimens are markedly stronger and stiffer than the across-axis ones.",
    discipline: "BIOMEDICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["biomechanics", "conceptual"],
    skillAreas: ["biomechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain why the strength and stiffness depend on the loading direction. Tie your answer to bone microstructure and to how the bone is normally loaded in life.", rubric: "Should identify anisotropy (direction-dependent properties); cortical bone is roughly transversely isotropic. Microstructural basis: osteons, lamellae, and collagen fibers with mineral (hydroxyapatite) are preferentially aligned along the bone's long axis, so the strong, stiff direction coincides with the dominant in-vivo load (axial compression/bending during gait). Loading across the grain loads weaker interfaces (cement lines, inter-osteon matrix), giving lower modulus and strength. This is a functional adaptation: structure is optimized for habitual load direction. Key insight: bone is anisotropic because its mineralized collagen architecture is aligned with the loads it normally carries, so a single isotropic stiffness/strength value misrepresents it." },
      { prompt: "Now the constraints change. A surgeon must drill a transverse hole through the shaft to place a screw. Using the anisotropy and the idea of a stress concentration, explain why and where the bone is most likely to crack, and what loading scenario makes this most dangerous.", rubric: "Should note the drilled hole is a stress concentrator (local stress raised by a factor of roughly 3 for a circular hole in tension), reducing fatigue and fracture strength. Cracks tend to initiate at the hole edge where stress peaks, and bone's weaker transverse/interfacial planes plus its brittleness under tension make crack propagation easier; torsional or bending loads that put the hole region into tension are most dangerous (bone is weaker in tension than compression). Combined with anisotropy, cracks run along the weak planes between osteons. Mitigation context: avoid sharp edges, limit hole size, protect from high torque early. Key insight: a hole both removes load-bearing material and concentrates stress, and because bone is brittle, anisotropic, and weakest in tension, that concentration is where fracture starts." },
    ],
  },
  {
    id: "biomechanics_gait_joint_loading",
    slug: "concept-biomechanics-gait-joint-loading",
    title: "Why the Hip Sees More Than Body Weight",
    prompt: "A biomechanics study reports that during single-leg stance in walking, the compressive force on the hip joint is roughly three times body weight, even though only one body weight is being supported by that leg at that instant.",
    discipline: "BIOMEDICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["biomechanics", "conceptual"],
    skillAreas: ["biomechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Using a free-body / moment-balance argument about the pelvis in single-leg stance, explain why the joint reaction force greatly exceeds body weight. Identify the key lever arms and the muscle responsible.", rubric: "Should set up moment balance about the hip joint center in the frontal plane: body weight (minus the stance leg) acts at the body center of mass, medial to the joint, with a relatively long moment arm; the hip abductors (gluteus medius/minimus) act on the greater trochanter with a short moment arm to hold the pelvis level. Because the abductor moment arm is much shorter than body weight's, abductor force must be large (roughly 2x body weight). The joint reaction = vector sum of body weight + abductor force, giving roughly 2.5-3x body weight. This is a Class-1-lever / unfavorable mechanical advantage situation. Key insight: a short muscle lever arm relative to the load's lever arm forces a large muscle force, and the joint must react both the load and that muscle force, so joint contact force far exceeds body weight." },
      { prompt: "Now the constraints change. A patient uses a cane in the hand opposite the affected hip. Explain mechanically how a cane on the contralateral side reduces the hip joint force so effectively, in terms of moments.", rubric: "Should explain that the cane in the opposite hand applies an upward support force with a long moment arm on the far side of the hip joint, creating a moment that opposes body weight's moment. This reduces the abductor force the body must generate to balance the pelvis, and because abductor force is the dominant contributor to joint reaction, even a modest cane force (with a long lever arm) sharply cuts the hip contact force. Contralateral placement maximizes the lever arm; ipsilateral would be far less effective or counterproductive. Key insight: a small force at a long lever arm can offset a large muscle force at a short lever arm, so an opposite-side cane unloads the hip far more than its own push-down force would suggest." },
    ],
  },
  {
    id: "biomechanics_implant_fatigue",
    slug: "concept-biomechanics-implant-fatigue",
    title: "An Implant That Broke Without Overload",
    prompt: "A femoral fracture-fixation plate is implanted and the patient is told to limit weight bearing. Eight months later the plate fractures across a screw hole, even though the patient never applied a single load anywhere near the plate's static strength.",
    discipline: "BIOMEDICAL",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["biomechanics", "conceptual"],
    skillAreas: ["biomechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Explain how the plate failed below its static strength. Use the concepts of cyclic loading, fatigue, stress concentration, and the typical role of a delayed bony union.", rubric: "Should identify fatigue failure: walking applies millions of sub-yield load cycles; cracks nucleate and grow until the remaining section fails, even though peak stress stays below the static/yield strength. The screw hole is a stress concentrator where the local cyclic stress is highest, so cracks initiate there. Crucially, if the fracture has not united (delayed/non-union), the plate alone carries the full cyclic load instead of sharing it with healing bone, so its cyclic stress amplitude stays high and it accumulates damage. Concept of S-N behavior / endurance limit; fatigue life depends on stress amplitude and number of cycles. Key insight: repeated everyday loads accumulate fatigue damage at stress raisers, and a plate that must bear load alone because the bone has not healed is in a race between bone union and its own fatigue life." },
      { prompt: "Now the constraints change. The design team wants the next plate to last longer in this delayed-union scenario. Explain the trade-off between simply making the plate stiffer/thicker versus the surgeon promoting faster bone healing, and why a stiffer plate is not automatically the safer fix.", rubric: "Should explain that a stiffer/thicker plate lowers its own cyclic stress and improves its fatigue life, but it also shields the fracture from load (stress shielding), reducing the mechanical stimulus bone needs to heal and remodel, which can prolong non-union and keep the plate bearing load longer. Some interfragmentary micromotion actually promotes callus formation (controlled flexibility / strain theory of healing). The durable fix is to get the bone to share load (faster union via biology, bone graft, adjusting fixation stiffness), not just to over-build the plate. Trade-off: fatigue safety of the hardware vs biological healing stimulus. Key insight: making the implant stiffer can win the fatigue battle but lose the healing war, because bone needs mechanical load to unite and ultimately take over from the plate." },
    ],
  },
  {
    id: "biomechanics_muscle_lever_elbow",
    slug: "concept-biomechanics-muscle-lever-elbow",
    title: "The Costly Lever of the Elbow",
    prompt: "Someone holds a dumbbell in the hand with the elbow bent at ninety degrees. The biceps inserts on the forearm only a few centimeters from the elbow joint, while the dumbbell sits roughly thirty centimeters from the joint at the hand.",
    discipline: "BIOMEDICAL",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["biomechanics", "conceptual"],
    skillAreas: ["biomechanics"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Using a moment balance about the elbow, explain why the muscle force is several times larger than the weight being held, and what the body trades away to be built this way.", rubric: "Should write moment balance about the elbow: muscle force times its short moment arm (a few cm) equals weight times its long moment arm (roughly 30 cm), so muscle force is roughly the ratio of lever arms (around 6-10x) larger than the load. This is mechanical disadvantage (third-class lever): the body sacrifices force to gain speed and range of motion at the hand, since a small muscle shortening produces a large, fast hand movement. Joint reaction force is correspondingly high. Key insight: the musculoskeletal system trades force for speed and range of motion, so muscles routinely generate forces many times the external load because their lever arms are short." },
      { prompt: "Now the constraints change. The person fully extends the elbow so the arm is nearly straight, then tries to hold the same dumbbell. Explain how the required muscle force and the muscle's ability to produce it change as joint angle changes, referencing the moment arm and the muscle's length-tension relationship.", rubric: "Should note that as the elbow angle changes, the muscle's effective moment arm changes (often largest near mid-flexion and smaller near full extension/flexion), so a smaller moment arm demands more muscle force for the same external torque. Simultaneously the load's moment arm changes with forearm orientation. The muscle's force capacity also varies with length via the length-tension (force-length) relationship: at very long or very short sarcomere lengths active force drops (optimal overlap at intermediate length); passive tension rises at long lengths. Net required vs available force can make some angles much weaker (a sticking point). Key insight: the torque a muscle can deliver depends jointly on its angle-dependent moment arm and its length-tension state, so strength is highly posture-dependent rather than constant." },
    ],
  },
];
