import type { PracticeProblem } from "../types";

export const problems: PracticeProblem[] = [
  {
    id: "sensors_actuators_accuracy_vs_precision",
    slug: "concept-sensors-actuators-accuracy-vs-precision",
    title: "Accuracy vs Precision on a Production Load Cell",
    prompt: "You are validating a load cell on a packaging line that targets 500.0 g fills. Across 50 trials of a known 500.0 g reference mass the cell reports values tightly clustered between 503.1 g and 503.4 g.",
    discipline: "MECHATRONICS",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["sensors-actuators", "conceptual"],
    skillAreas: ["sensors-actuators"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Characterize this sensor in terms of accuracy and precision, and explain what the data tells you about the dominant error type and how you would correct it.", rubric: "Excellent answer notes the readings are precise (low spread, ~0.3 g range, high repeatability) but inaccurate (consistent +3 g offset from the true 500.0 g). Identifies a systematic/bias error, not random error. States the fix is calibration: apply an offset (and ideally a multi-point span check) rather than averaging more samples, because averaging does not remove bias. Distinguishes accuracy (closeness to true value) from precision (closeness of repeated readings to each other). Key insight: precision and accuracy are independent; a repeatable systematic offset is removable by calibration whereas random scatter is not." },
      { prompt: "Part 2: Now the constraints change: after offset calibration, the readings instead scatter randomly between 497 g and 503 g with no consistent bias. What changed in error character, and would simply averaging readings or adding samples fix it?", rubric: "Notes the error is now random/noise-dominated (low precision) rather than systematic, so calibrating an offset will not help. Averaging N independent samples reduces random error standard deviation by sqrt(N), so averaging or filtering does help reduce the reported spread, unlike the bias case. Mentions investigating root causes: electrical noise, mechanical vibration, temperature drift, loose mounting, or insufficient excitation. Distinguishes that range/resolution and settling time may bound how much averaging helps. Key insight: averaging suppresses zero-mean random error (by sqrt(N)) but does nothing to a systematic bias, so you must first diagnose which error type dominates." },
    ],
  },
  {
    id: "sensors_actuators_wheatstone_strain",
    slug: "concept-sensors-actuators-wheatstone-strain",
    title: "Why a Wheatstone Bridge for Strain",
    prompt: "A junior engineer proposes measuring strain by wiring a single foil strain gauge in series with a fixed resistor and reading the voltage across the gauge with an ADC. The expected strain produces only about a 0.1 percent change in gauge resistance.",
    discipline: "MECHATRONICS",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["sensors-actuators", "conceptual"],
    skillAreas: ["sensors-actuators"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain why a Wheatstone bridge is strongly preferred over the simple voltage-divider approach for this measurement.", rubric: "Excellent answer explains that strain causes a tiny fractional resistance change (dR/R ~ GF * strain, gauge factor ~2), so the signal of interest is a very small change riding on a large baseline voltage. A divider buries this in a large DC offset, wasting ADC dynamic range and demanding impractical resolution. The bridge is balanced so its output is near zero at no-load and outputs only the differential change (Vout proportional to dR/R times excitation), so the full ADC range and gain can be applied to the small signal. A differential output also rejects common-mode noise. Key insight: the bridge converts a small fractional change on a large baseline into a near-zero-referenced differential signal, maximizing usable resolution and sensitivity." },
      { prompt: "Part 2: Now the constraints change: the structure sees large temperature swings and the gauge is far from the conditioning electronics on long lead wires. How would you modify the bridge configuration to handle this, and why does it work?", rubric: "Excellent answer proposes a half- or full-bridge using additional gauges, including a dummy/compensation gauge mounted on unstrained material at the same temperature so thermal resistance changes appear in adjacent arms and cancel (temperature compensation). A full bridge with gauges placed to sense equal-and-opposite strain (e.g. opposite faces of a bending beam) both compensates temperature and boosts sensitivity. For long leads, use a 3-wire (or 4-wire/Kelvin) connection so lead resistance and its temperature drift appear symmetrically and cancel rather than adding an error in one arm. Key insight: placing compensating gauges in adjacent bridge arms makes common-mode effects (temperature, lead resistance) cancel while the wanted differential strain signal adds." },
    ],
  },
  {
    id: "sensors_actuators_signal_conditioning_noise",
    slug: "concept-sensors-actuators-signal-conditioning-noise",
    title: "Conditioning a Noisy Thermocouple Signal",
    prompt: "A thermocouple on a motor housing produces a few-millivolt signal that runs alongside a variable-frequency drive cable into a 12-bit ADC. The logged temperature shows large jitter and an occasional jump that tracks when the motor switches.",
    discipline: "MECHATRONICS",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["sensors-actuators", "conceptual"],
    skillAreas: ["sensors-actuators"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Diagnose the likely noise mechanisms and lay out a signal-conditioning chain that would clean this up before the ADC.", rubric: "Excellent answer identifies the tiny millivolt signal is vulnerable to coupled noise: capacitive/inductive coupling from the VFD cable (EMI), ground loops, and common-mode pickup. Conditioning chain: instrumentation/differential amplifier with high CMRR near the source to amplify the differential signal and reject common-mode noise, shielded/twisted-pair cabling grounded at one end, gain to use ADC range, and an anti-aliasing low-pass filter set below Nyquist to remove high-frequency switching noise before sampling. Notes amplifying close to the source before noise pickup improves SNR. May mention cold-junction compensation for the thermocouple. Key insight: amplify the differential signal with high CMRR near the source and band-limit before the ADC, because once switching noise aliases into the sampled band no digital filter can recover the true signal." },
      { prompt: "Part 2: Now the constraints change: cabling and amplifier are fixed and the noise is dominated by the 50/60 Hz mains plus its harmonics, while the real temperature changes over seconds. What filtering strategy do you choose and what is the tradeoff?", rubric: "Excellent answer notes the signal of interest is very low bandwidth (seconds), so an aggressive low-pass with cutoff well below 50/60 Hz, or a notch filter at the mains frequency and harmonics, is appropriate. A strong option is a sigma-delta ADC or integrating measurement with conversion time set to an integer number of mains periods so 50/60 Hz integrates to zero (line-frequency rejection). Tradeoff: heavier low-pass filtering or longer integration increases response latency/settling time and reduces effective bandwidth, which is acceptable here because the process is slow. Key insight: exploit the wide separation between signal bandwidth and noise frequency, accepting added latency to gain large noise rejection, since the process dynamics are slow enough to tolerate it." },
    ],
  },
  {
    id: "sensors_actuators_motor_selection",
    slug: "concept-sensors-actuators-motor-selection",
    title: "Actuator Selection for a Pick-and-Place Axis",
    prompt: "You must drive a horizontal pick-and-place axis that needs fast, repeatable point-to-point moves to several fixed positions, modest payload, and quiet operation. A colleague suggests a stepper motor in open loop because it is cheap and easy.",
    discipline: "MECHATRONICS",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["sensors-actuators", "conceptual"],
    skillAreas: ["sensors-actuators"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Compare a stepper versus a servo (brushless DC with encoder) for this application and justify a recommendation.", rubric: "Excellent answer contrasts open-loop steppers (high holding torque at low speed, simple position-by-counting, no feedback, but risk of lost steps under overload, torque falls off sharply at high speed, resonance, and can run hot/noisy holding position) versus servos (closed-loop with encoder, high torque-to-inertia and better high-speed torque, smooth quiet motion, but higher cost and tuning complexity). For fast repeatable moves with confidence in position, recommends a servo or at least a closed-loop stepper, justifying based on speed, missed-step risk, and verified positioning. Considers inertia matching and duty cycle. Key insight: the open-loop stepper's lack of feedback means a missed step goes undetected, so the choice hinges on whether the application can tolerate undetected position error at the required speed." },
      { prompt: "Part 2: Now the constraints change: the axis must instead hold a heavy load stationary against gravity on a vertical axis for long periods between rare, slow moves. How does this shift your actuator choice and what failure modes now matter most?", rubric: "Excellent answer recognizes the duty cycle is now mostly static holding against gravity, where continuous holding current causes heating and a servo must actively fight gravity (potential runaway/back-drive on power loss). Favors solutions with passive holding: a stepper or servo combined with a power-off (fail-safe) brake, or a self-locking transmission such as a worm gear or high-ratio leadscrew so the load holds without continuous torque. Key failure modes: back-driving and dropping the load on power loss, thermal limits from continuous holding torque, and gravity-induced creep. Key insight: when the dominant duty is holding against gravity, you design for passive/fail-safe holding (brake or self-locking drivetrain) so a power loss does not drop the load, rather than relying on continuous actuator torque." },
    ],
  },
  {
    id: "sensors_actuators_backlash",
    slug: "concept-sensors-actuators-backlash",
    title: "Backlash in a Geared Positioning Stage",
    prompt: "A geared rotary stage uses a motor with an encoder on the motor shaft, driving the output through a spur-gear reducer. Commanded moves in one direction land accurately, but every time the stage reverses direction the output lags the command by a small, repeatable angle before it starts moving.",
    discipline: "MECHATRONICS",
    difficulty: "HARD",
    eloWeight: 26,
    tags: ["sensors-actuators", "conceptual"],
    skillAreas: ["sensors-actuators"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain the physical cause of this reversal lag and why placing the encoder on the motor shaft fails to detect it.", rubric: "Excellent answer identifies backlash: clearance between meshing gear teeth means on reversal the driving tooth must traverse the gap before re-engaging the opposite flank, so the output does not move while the motor turns through the lost motion. Because the encoder is on the motor (input) side of the gear train, it counts motor rotation that is taken up by the backlash gap and never reaches the output, so the controller believes it has moved when the output has not (the gearbox compliance/lash is outside the feedback loop). Notes it is repeatable and direction-dependent (only on reversal). Key insight: feedback taken before the source of lost motion cannot observe or correct that lost motion, so motor-side encoding hides backlash that an output-side measurement would reveal." },
      { prompt: "Part 2: Now the constraints change: you cannot replace the gearbox. List approaches to mitigate or eliminate the backlash error and the cost or limitation of each.", rubric: "Excellent answer lists options: (1) move the encoder to the output shaft (load-side feedback) so the loop closes around the backlash, eliminating the error but adding cost/complexity and possible loop stability concerns from gearbox compliance; (2) software backlash compensation that adds the known lash on each reversal, cheap but only as good as the model and degrades as wear changes the lash; (3) approach every target from the same direction (unidirectional positioning) so backlash never enters, costing time/throughput; (4) preloaded anti-backlash gears, split/spring-loaded gears, or a preloaded drivetrain that removes clearance, adding friction, wear, and reduced efficiency. May mention dual-motor preload or worm/harmonic drives with low lash. Key insight: you either measure past the lash (load-side feedback), avoid exciting it (single-direction approach), model and add it back (compensation), or mechanically preload it out, each trading off accuracy against cost, throughput, friction, or robustness to wear." },
    ],
  },
  {
    id: "sensors_actuators_resolution_vs_range",
    slug: "concept-sensors-actuators-resolution-vs-range",
    title: "Resolution vs Range in Displacement Sensing",
    prompt: "You are specifying a displacement sensor and a 16-bit ADC for a stage. The full mechanical travel is 100 mm, but the precision feature you actually care about requires resolving motion to about 1 micrometer.",
    discipline: "MECHATRONICS",
    difficulty: "MEDIUM",
    eloWeight: 26,
    tags: ["sensors-actuators", "conceptual"],
    skillAreas: ["sensors-actuators"],
    evaluationMode: "LLM_GRADED",
    parts: [
      { prompt: "Part 1: Explain the tension between range and resolution here, and assess whether mapping the full 100 mm range onto the 16-bit ADC can meet the 1 micrometer requirement.", rubric: "Excellent answer frames resolution as range divided by the number of distinguishable levels: a 16-bit ADC gives 65536 levels, so spanning 100 mm yields about 100 mm / 65536 = ~1.5 micrometers per LSB. That barely meets (or fails) a 1 micrometer requirement once noise (effective number of bits below 16) is considered, leaving essentially no margin. States the core tradeoff: for a fixed bit depth, widening range coarsens resolution and vice versa; you cannot get both fine resolution and full range from the same fixed-bit map without help. Distinguishes quantization step (resolution) from total range and from accuracy. Key insight: resolution = range / levels, so for fixed ADC bits range and resolution trade directly, and quoting bit count alone is meaningless without the range it is mapped over and the real noise floor." },
      { prompt: "Part 2: Now the constraints change: you must keep the full 100 mm travel yet truly resolve 1 micrometer with margin. What architectures let you escape the single-fixed-range tradeoff, and what new problems do they introduce?", rubric: "Excellent answer offers options: (1) higher-resolution ADC or a more sensitive/higher-resolution sensor (more levels over the same range); (2) a dual-sensor / coarse-fine architecture, e.g. a long-range coarse encoder plus a short-range high-resolution sensor (capacitive/interferometric) for the precision feature, requiring stitching/handoff between sensors; (3) programmable-gain or auto-ranging front end that zooms the ADC onto the region of interest, introducing range-switching transients and the need to track absolute position; (4) incremental/interpolated encoders that subdivide a fine pitch over long travel. New problems: calibration and alignment between coarse and fine domains, ensuring the noise floor and sensor linearity actually support 1 micrometer (not just the ADC), thermal drift over 100 mm, and added cost/complexity. Key insight: you break the fixed range-vs-resolution tradeoff by splitting it across coarse and fine measurement domains (or raising the level count), but then the limiting factor shifts from quantization to the noise floor, linearity, and the calibration that ties the domains together." },
    ],
  },
];
